### ISSUE TITLE
Sound crackles on first boot and on system use

### ISSUE THREAD

**Issue by maxengel** [stockmind/gpd-pocket-ubuntu-respin#10]
When going through installation, the audio crackles during the standard Ubuntu "drumroll."

**Comment by guidouil** [comment]
Same here, but I think it's because of the speaker... I have the same on youtube after installation.
Just lower the volume

**Comment by maxengel** [comment]
Hrm. I've seen this reported elsewhere as a known issue on Ubuntu with the GPD Pocket, so maybe it is a driver issue?

**Comment by stockmind** [comment]
Probably a driver issue. For me audio is not that great also on Windows. I can hear crackling sometimes, but seems to work fine randomly other times.

**Comment by maxengel** [comment]
Interesting. Do you think that the driver will be fixed upstream, or is it a GPD-specific issue?

**Comment by stockmind** [comment]
I hope is only a driver thing that will get addressed hopefully (It may take a while...).
It may also be possible that it's just due to poor speakers quality or wrong volume settings. (On mid volume my audio is fine)

**Comment by cawilliamson** [comment]
I keep hearing this "it's just bad hardware" tail and it's nonsense.

I've checked on Windows at high volumes and yes, there is some distortion but at mid - mid-high volumes there's no distortion at all. It's not exactly studio quality of course but there is no crackling.

At ANY volume on Linux I'm experiencing crackling - noise distortion, etc. Videos, startup tune, music on spotify - it ALL sounds unbearable because of the constant crackling.

I'm sure there is a fix somewhere for this but right now it's insufferable!

**Comment by stockmind** [comment]
Just asking: headphones works for you? Mine seems to work only on kernel 4.13.
I've the crackling noise also on headphones so it's probably a driver issue.
I've opened an issue on chtrt5645 original repository, will update if something comes up.

**Comment by mattstx** [comment]
Same issue.  But only with headphones.  Audio has no issue from internal speaker.  Kernel is 4.12.  Windows has no issue from headphones or speaker.  Pulse does run at 100% when output to speakers is selected.

**Comment by stockmind** [comment]
Hi mattstx, what BIOS version are you using? Also are you using kernel 4.12-rc7 or 4.12 builded from Hans repository?

**Comment by mattstx** [comment]
Bios: 2.17.1249 - The latest.
Kernel: 4.12.0-rc7-custom.

Side note, the internal microphone is not working for me, nor is the microphone on the headset jack.

Workaround:
USB headset such as a Plantronics USB 655 or the couple random Logitech ones I tested with Linux work great.

**Comment by cawilliamson** [comment]
This one is already open but no response so far:

https://bugzilla.kernel.org/show_bug.cgi?id=196351

Pretty poor support from the ALSA devs on this so far to be honest - probably going to harass them via email - I'm sure Hans gave me a contact at one point - I should drop them an email and see what's going on.

**Comment by stockmind** [comment]
I've linked it to plbossart from Intel ad he has just added Bard Liao from Realtek.
We'll see if they can help fix it now! :)

**Comment by cawilliamson** [comment]
Awesome news - just providing some info on the bugzilla ticket.

Could you invite hans to the ticket too (if you're the one who raised it?) - I think he should probably be involved on this one since he's the one who disabled realtime-scheduling in pulse - not sure why he did that or why it was needed so maybe he can shed some light on that.

**Comment by ThuggishNuggets** [comment]
In the meantime, if you have a [PS4 Gold Wireless headset](https://www.amazon.com/PlayStation-Gold-Wireless-Stereo-Headset-4/dp/B00HVBPRUO?th=1), this works beautifully with the GPD Pocket on Ubuntu 16.04 and 17.04 with 4.12 and 4.13 kernels, no additional drivers. As a bonus, the headset's built-in microphone also works.

**Comment by stockmind** [comment]
This sounds good https://bugzilla.kernel.org/show_bug.cgi?id=196351#c25
I'm building a new kernel with that flag off, i will upload to you for testing as my unit is dead

**Comment by maxengel** [comment]
I also know Ubuntu 17.10 is supposed to have some audio fixes. My unit is dead too.

**Comment by stockmind** [comment]
My unit was probably already defective from the unbox, it just survived luckily until now as it sometimes refused to boot (rarely, a reseat of battery was enough to fix this) or took a lot to show the GPD logo (with stock bios, on later bios it seemed disappeared but reappared lately until it stopped to boot with white led on and nothing on screen), my unit was first generation and i was one of the first that received it so i'm not really surprised, yours what problem have? Sorry for OT.

**Comment by maxengel** [comment]
I had odd power issues and screen bleeding issues, as well as some other hardware problems. Unfortunately, they made me pay $50 USD for return shipping, and then just sent me back the exact same unit without doing a single thing to it. They now have refused to respond to my emails or acknowledge the issue. Nor will they refund my shipping, which they earlier promised to. Honestly, I'm fed up with them as a company, considering we're trying to help their product...

On Oct 10, 2017, at 10:14 AM, stockmind <notifications@github.com> wrote:

My unit was probably already defective from the unbox, it just survived luckily until now as it sometimes refused to boot (rarely, a reseat of battery was enough to fix this) or taked a lot to show the GPD logo (with stock bios, on later bios it seemed disappeared but reappared lately until it stopped to boot with white led on and nothing on screen), my unit was first generation and i was one of the first that received it so i'm not really surprised, yours what problem have? Sorry for OT.

**Comment by stockmind** [comment]
I'm really sorry for you and hope they change their mind about your refund. It's not correct to change mind like that for a company, no matter how tiny is, at least without look for a compromise.

Here is the new kernel with flag for audio fix for anyone with a working GPD https://bitbucket.org/simone_nunzi/gpdpocket-kernel/downloads/gpdpocket-20171010-kernel-files-audio-fix.zip

**Comment by parkerlreed** [comment]
@stockmind I can confirm from my end that on the Pocket that does indeed reduce the crackling to on par with Windows.

**Comment by evilJazz** [comment]
From what I just saw nexus511's kernel using the Ubuntu config also has CONFIG_INTEL_ATOMISP disabled, but has other issues on my GPD Win, namely BT not working and SD card tray only working with non-SanDisk/UHS SD cards (patch soon). Glad I didn't waste my time in vain.

**Comment by parkerlreed** [comment]
@evilJazz Bluetooth has been working on my Pocket since Han's 4.14-rc2. Maybe the nexus511 build just needs an update?

**Comment by evilJazz** [comment]
@parkerlreed Yes, nexus511 kernel requires an update I guess. With Hans' kernel always worked on the GPD Win when manually hooking up the UART via hciattach. I think the Pocket had BT enabled both via USB and via UART which caused issues previously and Hans fixed it in a recent commit.

**Comment by snazzybunny** [comment]
Bluetooth is finicky for me. Sound cuts off and gets choppy after a few minutes and then returns back to normal again. What about the microphone on linux, it seems it only works on Windows.

**Comment by parkerlreed** [comment]
Yeah Bluetooth varies for me also. If I stay close range it manages A/V sync fine but as soon as I move maybe 6-7 feet away headphones will drop and try to catch up. Usually have to pause the video (mpv) for a few seconds to get back to normal.

**Comment by stockmind** [comment]
Maybe related too poor signal of internal antenna?

Il 11 ott 2017 13:02, "parkerlreed" <notifications@github.com> ha scritto:
