### ISSUE TITLE
GNOME 3: Cannot login after sleep

### ISSUE THREAD

**Issue by karelbilek** [stockmind/gpd-pocket-ubuntu-respin#100]
I have downloaded and installed latest respin Ubuntu (`gpdpocket-20180124-ubuntu-17.10.1-desktop-amd64.iso`).

Everything works great, BUT I cannot log in after sleep!

I see just date and time. I can tap anywhere, it seems touchscreen works, mouse works (I can select things in the top menu), but I cannot log in! I don't see any usernames.

**Comment by karelbilek** [comment]
I don't know if this is regression or not, I have just installed Linux on GDP Pocket for the first time

**Comment by karelbilek** [comment]
ctrl-alt-F1 worked, but now everything is in landscape again. And  the button for switching the orientation disappeared.

**Comment by karelbilek** [comment]
This happened just once and I cannot replicate it. (Now after sleep, I still have wrong orientation, but the tray icon stays there.) So it is fine I guess, I will close for now

**Comment by karelbilek** [comment]
It happens quite frequently, I always dread to see the time lockscreen.

Hoever the portrait switching usually stays on, so I just have to push ctrl+slt+fn+f1 and/or f2, switch back and forth and log in repeatedly until it works.

Not ideal.

**Comment by karelbilek** [comment]
I have noticed that the login/password form is actually there, just not visible.

So you can press enter and then blindly enter your password, even when ubuntu just shows the lockscreen,

**Comment by stockmind** [comment]
Try to switch to Unity and Lightdm as suggested #101 , your problems should disappear! :)
