### ISSUE TITLE
GNOME 3: External display not working properly

### ISSUE THREAD

**Issue by karelbilek** [stockmind/gpd-pocket-ubuntu-respin#101]
I have `gpdpocket-20180124-ubuntu-17.10.1-desktop-amd64.iso`

External display is so much not working that I basically need to turn computer off and on before connecting and/or disconnecting it :(

When I have the external display and I disconnect it, I sometimes don't see anything on the small screen, not the login or anything. This is annoying, I basically cannot connect and disconnect HDMI on the go

**Comment by stockmind** [comment]
Hi! Are you using GNOME? Have you tried to use Unity and switch to lightdm?
I've got lot of troubles with GNOME. 

You can install unity with:

    sudo apt-get install unity

To install and use lightdm execute

    sudo apt-get install lightdm

When prompted select "lightdm" as display/login manager.

Attach HDMI only after the device is powered on. It may not work if you plug it before boot, or you can encounter strange behaviour.

Also if you don't see any signal on external monitor or screen is glitched try to play around with the "Monitor" system window.

Also do you mind to post output of "problem-reporting.sh" script of this repository? Thanks!

**Comment by karelbilek** [comment]
Hm. I am using gnome, since that is default on ubuntu now. I will try unity later. Thx for tip.

**Comment by stockmind** [comment]
If you want to stick with GNOME try to run `update.sh gnome` script of this repository. Mind the `gnome` argument is important. If you choose to use Unity run `update.sh` script without the `gnome` argument so the script will change monitors.xml with the right one. Let me know if this helps
