### ISSUE TITLE
gpdfand.service fails to start

### ISSUE THREAD

**Issue by vjoel** [stockmind/gpd-pocket-ubuntu-respin#103]
I noticed today that the fan was running constantly when on A/C (even when suspended). The fan stops on switching to battery.

The actual temperature is quite low (36C according to /sys/devices/platform/coretemp.0/hwmon/hwmon3/temp5_input).

This started happening after applying the early Feb commits this morning using update.sh and then rebooting. I then did update-kernel.sh (which downloaded gpdpocket-20180207-kernel-files.zip), but that did not seem to affect the fan behavior, even after another reboot.

(I'm pretty sure I applied all the Jan. commits and did not see this behavior. The fan almost never runs since I started using this respin months ago.)

It seems the service cannot access the gpio device:

```
> sudo systemctl status gpdfand.service 
● gpdfand.service - GPD Fan Daemon
   Loaded: loaded (/etc/systemd/system/gpdfand.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-02-09 14:09:54 PST; 4s ago
  Process: 10759 ExecStart=/usr/local/sbin/gpdfand --time=${TIME} --turbo=${TURBO} --min=${MIN} --med=${MED} --max=${
 Main PID: 10759 (code=exited, status=1/FAILURE)

Feb 09 14:09:54 gpdpocket systemd[1]: Started GPD Fan Daemon.
Feb 09 14:09:54 gpdpocket gpdfand[10759]: Traceback (most recent call last):
Feb 09 14:09:54 gpdpocket gpdfand[10759]:   File "/usr/local/sbin/gpdfand", line 63, in <module>
Feb 09 14:09:54 gpdpocket gpdfand[10759]:     init()
Feb 09 14:09:54 gpdpocket gpdfand[10759]:   File "/usr/local/sbin/gpdfand", line 60, in init
Feb 09 14:09:54 gpdpocket gpdfand[10759]:     gpio_export.write(unicode(id))
Feb 09 14:09:54 gpdpocket gpdfand[10759]: IOError: [Errno 16] Device or resource busy
Feb 09 14:09:54 gpdpocket systemd[1]: gpdfand.service: Main process exited, code=exited, status=1/FAILURE
Feb 09 14:09:54 gpdpocket systemd[1]: gpdfand.service: Unit entered failed state.
Feb 09 14:09:54 gpdpocket systemd[1]: gpdfand.service: Failed with result 'exit-code'.

```

If I restart the service, the error is the same.

I'm running Xubuntu 16.04. My BIOS is the "locked down" one.

**Comment by vjoel** [comment]
If it helps:

```
/sys/class/gpio> ls -l
total 0
--w------- 1 root root 4.0K Feb  9 15:48 export
lrwxrwxrwx 1 root root    0 Feb  9 15:56 gpiochip315 -> ../../devices/platform/INT0002:00/gpio/gpiochip315/
lrwxrwxrwx 1 root root    0 Feb  9 15:43 gpiochip318 -> ../../devices/platform/INT33FF:03/gpio/gpiochip318/
lrwxrwxrwx 1 root root    0 Feb  9 15:43 gpiochip373 -> ../../devices/platform/INT33FF:02/gpio/gpiochip373/
lrwxrwxrwx 1 root root    0 Feb  9 15:43 gpiochip397 -> ../../devices/platform/INT33FF:01/gpio/gpiochip397/
lrwxrwxrwx 1 root root    0 Feb  9 15:43 gpiochip456 -> ../../devices/platform/INT33FF:00/gpio/gpiochip456/
--w------- 1 root root 4.0K Feb  9 15:43 unexport
```


That doesn't seem consistent with the code that writes to the gpio:

```
def set_fans(a,b):
    with io.open('/sys/class/gpio/gpio397/value', 'w') as gpio:
        gpio.write(unicode(a))
    with io.open('/sys/class/gpio/gpio398/value', 'w') as gpio:
        gpio.write(unicode(b))

```

and

```
def init():
    for id in [397,398]:
        if not os.path.isfile('/sys/class/gpio/gpio' + str(id) + '/value'):
            with io.open('/sys/class/gpio/export', 'w') as gpio_export:
                gpio_export.write(unicode(id))

```

**Comment by stockmind** [comment]
Can you post output of "problem-reporting.sh" script of this repository? Thank you

**Comment by vjoel** [comment]
```
**Kernel:** 4.15.0-stockmind-gpdpocket
**Desktop Environment:** 
**Display:** :0.0
**Login:** ExecStart=/usr/sbin/lightdm
**Monitor:** DSI1 connected 1920x1200+0+0 right (normal left inverted right x axis y axis) 0mm x 0mm
**Scripts:**  gpdfand gpdscreen gpdscreen-indicator
**EFI:**  [ 0.000000] efi: EFI v2.40 by American Megatrends
**EFI**  Release Date: 08/07/2017

```

**Comment by vjoel** [comment]
not sure why the script isn't picking up one var

```
> echo "**Desktop Environment:** $XDG_CURRENT_DESKTOP"
**Desktop Environment:** XFCE

```

**Comment by stockmind** [comment]
Two months ago Hans de Goede pushed a proper fan driver for kernel:
https://www.reddit.com/r/GPDPocket/comments/7jiv3g/linux_proper_fan_driver_submitted_for_mainline/

The gpdfand daemon fail when the module for gpd_fan gets loaded from kernel.
You can check this by issuing:

`lsmod | grep gpd`

On kernel like 4.14 the daemon will run without issues, but i keep the daemon just for the moment, to let fan work on kernels that doesn't ship with the Hans driver included, so it is possible to switch kernels and try different configs without tinker too much with basic things (same approach for bluetooth).

The problem of the fan always on happen only on latest kernel i've built. If you install and use a previous kernel everything will work as expected:
https://bitbucket.org/simone_nunzi/gpdpocket-kernel/downloads/gpdpocket-20180115-kernel-files.zip

https://bitbucket.org/simone_nunzi/gpdpocket-kernel/downloads/

I'll try to build a new kernel and see if the problem persist.

**Comment by vjoel** [comment]
That works for me. I still had 4.14.0-rc5-audio-gpdpocket installed, and after booting that the userspace fan daemon is working.

The only downside of 4.14 is that (unlike 4.15) I have to manually start (or restart) the xfce4-volumed when I log in (no big deal).

Thanks for the help, and for all your work on this project.

**Comment by stockmind** [comment]
The kernel i linked should work good: https://bitbucket.org/simone_nunzi/gpdpocket-kernel/downloads/gpdpocket-20180115-kernel-files.zip
No need to use 4.14... The kernel fan driver by Hans works like a charm

**Comment by vjoel** [comment]
Just installed that kernel (4.15.0-rc7-stockmind-gpdpocket) and, yes, it works nicely.

**Comment by stockmind** [comment]
Updated README i will update you if i have news about the fan on A/C

**Comment by stockmind** [comment]
Just an update on this: https://github.com/stockmind/gpd-pocket-ubuntu-respin#gpd-fan-always-spinning-on-ac

I've added the kernel parameter required to shut down fan when not needed on AC :) Got explanations from Hans and put everything together. An "update.sh" run of my script will add the required parameter to GRUB so you can use new kernels without the always on fan "issue" on AC :)

Deamon will still not work, but you don't need that if you run latest kernels!

**Comment by vjoel** [comment]
Fan behavior is fine for me now, using 4.16.0-rc3-stockmind-gpdpocket. Thanks!
