### ISSUE TITLE
When should I run update?

### ISSUE THREAD

**Issue by pgeyman** [stockmind/gpd-pocket-ubuntu-respin#108]
Hi!

Thanks for all your great efforts!
I have successfully installed on my GPD Pocket, but I am unsure as to when I need to run your update script.

If I run apt-get dist-upgrade should I run it after that?

**Comment by stockmind** [comment]
Hi!

After First install, download repository and run update.sh to update
initramfs for console font size. After that you should run update script
when you choose to change main desktop environment (script detect
availables DE and install patches accordingly) or when new fixes are
available ( take a look to the commits once in a while).

Il 12 mar 2018 11:36, "pgeyman" <notifications@github.com> ha scritto:

**Comment by pgeyman** [comment]
Ok, thanks.

So I don't need to run it after "apt-get dist-upgrade"?

**Comment by stockmind** [comment]
Only if you encounter issues. Update script will simply fix/overwrite wrong configurations.
