### ISSUE TITLE
How Do You Start?

### ISSUE THREAD

**Issue by maxengel** [stockmind/gpd-pocket-ubuntu-respin#11]
I know this is a very simple question, so my apologies for being new to respinning. I'm trying to respin an ISO of Elementary OS. I understand the basic concept, but it would be really helpful to have steps numbered. For example, do I need to clone the directory locally first, and then put the ISO in that directory? I am unclear as to where to start...

**Comment by scofieldpeng** [comment]
1. clone the repo
2. download the iso(ubuntu,elementary os or Linux mint) and put into the repo dir
3. download the latest kernal then put into the dir
4. now run the build.sh <your iso>
it many take a about 30 minutes or even longer

notice that you need to run `sudo apt install -y git wget genisoimage bc squashfs-tools xorriso` when u run the `build.sh` script, good luck:-)

**Comment by maxengel** [comment]
Thanks! It would be great to have that at the top of the readme :-)

On Jul 26, 2017, at 03:30 AM, Scofield Peng <notifications@github.com> wrote:

clone the repo
download the iso(ubuntu,elementary os or Linux mint) and put into the repo dir
download the latest kernal then put into the dir
now run the build.sh 
it many take a about 30 minutes or even longer
notice that you need to run sudo apt install -y git wget genisoimage bc squashfs-tools xorriso when u run the build.sh script, good luck:-)

**Comment by stockmind** [comment]
Will update the README with running instructions, thanks for suggestion!

**Comment by maxengel** [comment]
Also, I am following the instructions, and building the kernel generates the following:
`error: index-pack died of signal 941245)   
fatal: index-pack failed
`

**Comment by stockmind** [comment]
On what environment are you? Arch, Debian or anything else? Building on Ubuntu 17.04 amd64 works fine. Latest builds are done directly from my GPD.
I've built another kernel from Hans repo and no issues using commands posted on README of this repo.
Will upload and update kernel files after some testing. Crashes may be solved on this one. Probably thanks to the brcmfmac patch.

**Comment by maxengel** [comment]
This wound up being a memory issue with the VM I was using to build it.

**Comment by stockmind** [comment]
Good to know! Thanks for the update! :) I close the issue

**Comment by maxengel** [comment]
A couple of issues:

1. I'm told that I need to "download kernel files" when I first run ./build.sh. I did this, and placed them in the same root directory, and the build proceeds
2. I built the kernel into the same root directory in the /linux-sunxi directory based on the instructions in "Debian based systems"
3. It is unclear which .zip file I am meant to overwrite. chrisaw-kernel-files.zip? Should that be deleted?
4. When I now run ./build.sh ...iso it generates "Kernel image not found" but does continue.
5. It then says "Extracting kernel files" but uses the archive "chrisaw-kernel-files.zip.
6. The guide makes it seem like you have to run ./build.sh twice: once to build the iso and once to put the latest kernel into the respin. Is that correct?
7. The iso builds correctly with the "linuxium" prefix.
8. The installer loads, initially in the right orientation, but then rotates to the wrong orientation.

I'll report any bugs post-installation as issues, but hopefully this helps refine the readme/instructions.

**Comment by stockmind** [comment]
I'm still fixing up some problems with rotation in Pantheon of Elementary OS.
Could you post a photo of wrong rotation? Thanks!
Also what BIOS version are you using?
Your suggestions are legit and will update README to improve it!

3. You should overwrite the zip requested by build.sh to work. I update and hardcode the name of updated kernel zip file when release new kernel to be sure that only right file is used.
4. It's debug print that is misleading, i will improve it

**Comment by maxengel** [comment]
So to clarify, that is the chrisaw-kernel-files.zip? If so, the instructions should say to delete that archive, and then replace it with the newly-created file from the compressed .deb files as indicated currently in the readme,

I'm using the latest BIOS.

I've identified other issues with elementary OS, and will create new issues for those. I'll try to take a photo/video, but it would require me to reinstall the OS.

**Comment by stockmind** [comment]
You don't need to build iso two times. The first time the script will simply print on screen for you the link of latest kernel package and ask you download before start the process.
That's due to lack of a good filehosting that let me use easily wget to download it automatically.
The build script will touch the ISO only one time and do everything when you call the "build.sh + iso file name" when kernel files are already inside folder.

To use a kernel compiled by you, you have to replace the latest kernel zip file with one that contains your builded files.
The kernel zip file name change when i update the build.sh to match latest kernel that i upload and is hardcoded inside the build script.

The part related to kernel building is mandatory at only needed if you want a custom build.

So the important steps are the first 2 of your new README.
Step 3 is mandatory.
Step 4 is a repetition of step 2 (and all the step included inside of this, so 2-1, 2-2, 2-3 ... etc)

I'm sorry if i've confused you.

**Comment by stockmind** [comment]
I can add a check that will build everything using custom kernel build if the file is present in folder, ignoring the usual one, so a user don't need to overwrite anything, just delete his builded one only if he want to use the "official" one of this repo

**Comment by maxengel** [comment]
I just submitted a pull request revamping the readme to address your feedback and clarifications. Hopefully this matches the process more accurately.
