### ISSUE TITLE
i3 window manager

### ISSUE THREAD

**Issue by sanenr9** [stockmind/gpd-pocket-ubuntu-respin#115]
Hello,

I am not sure, if this is connected to your work at all, but as you have such a big knowledge on the gpd pocket i just thought i add it here.

I set up your respin on Kubuntu and it worked great the last months with KDE plasma.

I now started using the cool tiling window manager i3wm, so i just logged out and back in with i3.

Everything is working fine, but Chromium-Browser and some other apps like Thunderbird are not scaling correctly (They are acting as if this was a huge hd screen and everything is really small).

I assume this is about GTK scaling settings. Could you advise which changes i have to do to achieve the same effect of "normal" scaling like under Plasma, that you so brilliantly achieved? Or could i even start one of your scripts from the respin and it will do the changes?

Thanks so much for your help!

Michael

**Comment by stockmind** [comment]
Hi!

Try this:
```
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
```

Or add to `/etc/environment` file and reboot:

```
GDK_SCALE=2
GDK_DPI_SCALE=0.5
```

This will do it for you:
```
echo "GDK_SCALE=2" >> /etc/environment
echo "GDK_DPI_SCALE=0.5" >> /etc/environment
```

The GPD Pocket screen (1920x1080) is like a "huge" high definition display compressed in 7" size. So GTK apps need to be upscaled accordingly to look acceptable.

GDK_SCALE however accept only integers, so you are tied to 1 (default) or 2 (2x original size).

This however is handled by other Desktop Environment so is possibile that you need to remove those lines from /etc/environment (to prevent odd behaviour) if you want to use different DE than i3.

Let me know if this helps

**Comment by sanenr9** [comment]
It worked! Thank you so much :+1:
