### ISSUE TITLE
Cinnamon Installation

### ISSUE THREAD

**Issue by guidouil** [stockmind/gpd-pocket-ubuntu-respin#12]
I tried to install Cinnamon instead of Unity and it was not so difficult but I still have some issues.
To install it just I just did `sudo apt-get install cinnamon-desktop-environment` and then choosed it in GDM at login.
But on cinnamon the sleep does not work anymore on lid closing also it ain't called sleep anymore but suspend.
Do you think of something to fix it ?
Also I prefer to have all the pixels on my screen and enlarge the fonts so I changed this file `/etc/X11/Xsession.d/90-scale` and set the `scaling-factor` to 1 and `text-scaling-factor` to 2.
Maybe you should point it out in the Readme ;)
Thanks for your help and time

**Comment by stockmind** [comment]
Will update README, thanks for suggestion!
I had respinned some Linux Mint Cinnamon ISO just for testing and didn't noticed that behaviour.
Will try it out and check if a fix is possible! You can also try clone my repo and launch the update.sh script on your system to update GDM conf!

**Comment by guidouil** [comment]
My bad, lid-closing do work. You just have to activate the `Perform lid-closed action even with external monitors attached` in the Power management settings
Maybe you can close this issue. Thanks :)
