### ISSUE TITLE
System freeze

### ISSUE THREAD

**Issue by c0nsu1tant** [stockmind/gpd-pocket-ubuntu-respin#120]
Hi. I read about this before and now have same issue.
Kernel 4.16.0-rc3-stockmind freeze when starting Chrome or Chromium
What should i do? Which is last stable kernel?

**Comment by stockmind** [comment]
Please follow "Have an issue?" section of the README. 
https://github.com/stockmind/gpd-pocket-ubuntu-respin#have-an-issue

Post output of problem-reporting script https://github.com/stockmind/gpd-pocket-ubuntu-respin#problem-reporting

Your BIOS version matter here.
Check this:
https://github.com/stockmind/gpd-pocket-ubuntu-respin#system-freeze-or-hangs-on-high-temperatures-high-load-or-randomly

Check previous issues for more informations:
#83
#78
#66
