### ISSUE TITLE
./docker-build-kernel.sh fails.

### ISSUE THREAD

**Issue by dmhursh** [stockmind/gpd-pocket-ubuntu-respin#122]
I'm guessing it's an out of date kernel config.  I got the same result with & without `keepconfig`.  It's just waiting for me to answer.  I assume this isn't supposed to happen?

```
$ ./docker-build-kernel.sh keepconfig
Input dir: /home/user/stockmind/gpd-pocket-ubuntu-respin/origin
Output dir: /home/user/stockmind/gpd-pocket-ubuntu-respin/destination
Found Docker Hub image!
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...] [flags]

Remove one or more containers
default via 172.17.0.1 dev eth0 172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.2
Gateway: 172.17.0.1
Internet test passed.
Cloning into './kernel-build'...
remote: Counting objects: 6302082, done.
remote: Compressing objects: 100% (1092/1092), done.
remote: Total 6302082 (delta 1190), reused 602 (delta 602), pack-reused 6300388
Receiving objects: 100% (6302082/6302082), 2.32 GiB | 1.80 MiB/s, done.
Resolving deltas: 100% (5215071/5215071), done.
Checking out files: 100% (61552/61552), done.
Using custom kernel config...
Processors in use for build 5
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  YACC    scripts/kconfig/zconf.tab.c
  LEX     scripts/kconfig/zconf.lex.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --syncconfig Kconfig
.config:1128:warning: symbol value 'm' invalid for NF_TABLES_INET
.config:1129:warning: symbol value 'm' invalid for NF_TABLES_NETDEV
.config:1315:warning: symbol value 'm' invalid for NF_TABLES_IPV4
.config:1320:warning: symbol value 'm' invalid for NF_TABLES_ARP
.config:1363:warning: symbol value 'm' invalid for NF_TABLES_IPV6
.config:1398:warning: symbol value 'm' invalid for NF_TABLES_BRIDGE
.config:6731:warning: symbol value 'm' invalid for DELL_SMBIOS_WMI
.config:6732:warning: symbol value 'm' invalid for DELL_SMBIOS_SMM
.config:7372:warning: symbol value 'm' invalid for NVMEM
*
* Restart config...
*
*
* ACPI (Advanced Configuration and Power Interface) Support
*
ACPI (Advanced Configuration and Power Interface) Support (ACPI) [Y/n/?] y
  AML debugger interface (ACPI_DEBUGGER) [N/y/?] n
  ACPI Serial Port Console Redirection Support (ACPI_SPCR_TABLE) [Y/n/?] y
  Deprecated power /proc/acpi directories (ACPI_PROCFS_POWER) [N/y/?] n
  Allow supported ACPI revision to be overridden (ACPI_REV_OVERRIDE_POSSIBLE) [N/y/?] n
  EC read/write access through /sys/kernel/debug/ec (ACPI_EC_DEBUGFS) [M/n/y/?] m
  AC Adapter (ACPI_AC) [Y/n/m/?] y
  Battery (ACPI_BATTERY) [Y/n/m/?] y
  Button (ACPI_BUTTON) [Y/m/?] y
  Video (ACPI_VIDEO) [M/y/?] m
  Fan (ACPI_FAN) [Y/m/?] y
  ACPI Time and Alarm (TAD) Device Support (ACPI_TAD) [N/m/y/?] (NEW) 
```

**Comment by stockmind** [comment]
The script was still looking for the .config in the origin directory, instead of the Hans one, fixed :)

**Comment by dmhursh** [comment]
I pulled the repo, built my own docker image with the script and reran this and got the same failure.  I'm on debian stable if that matters (docker and all).

Do I need to do something more or  different?  Sorry to be a pest.  I just want an xfce image (preferable mint vs ubuntu) that I can flash onto an unbootable gpd.  Can I just run `./docker-respin.sh linuxmint-18.3-xfce-64bit.iso`, boot the image it produces and then run `update.sh` & `update-kernel.sh` from the gpd?  (I'm not sure if steps 2a and 2b are both needed or if I can just pick one.)

Thanks

**Comment by stockmind** [comment]
Are you sure you have pulled latest commit?
Can you post me the output of `./docker-build-kernel.sh keepconfig` again?

Anyway two deps were missing to build the latest kernel, i've added them and will try to complete a build today

**Comment by dmhursh** [comment]
I'm on commit 42edf87f382ab9a9f496662da67d4a4c8559e294.

I suspect I may not have used my docker image yesterday.  If I'm reading the script right, it favors `stockmind/gpd-pocket-ubuntu-respin:latest` over `gpd-pocket-ubuntu-respin:latest`.  The build script only tags `gpd-pocket-ubuntu-respin:latest`.  I had an old copy of the one from docker hub at the time and I bet that was used.

I see there is a newer version of the image on dockerhub.  I pulled that and I'm running `./docker-build-kernel.sh keepconfig` again.  I'll let you know how that goes.  Thanks for you help.

**Comment by stockmind** [comment]
Thank you! I have completed a build succesfully and posted on bitbucket, it doesn't have the improvements for brightness on live environments and the optimized build for atom processors but should work

And you're right, originally i was prefering to use the docker hub image over the local one, but it's probably not user friendly as usually the local version should be the prefered one

**Comment by dmhursh** [comment]
Looks like it was just an old image.  It's past configuring and compiling code.  Once that's done I'll see how I put the kernel and iso together.  If I have trouble I'll see if I can find you bit bucket.  Thanks again.
