### ISSUE TITLE
Upgrade kernel and fan ?

### ISSUE THREAD

**Issue by adiif1** [stockmind/gpd-pocket-ubuntu-respin#126]
Hi all i have small question i can upgrade kernel from ( apt get upgrade? ) i use iso from [https://gpdpocket.cre.ovh/](url)

gpdpocket-unity-20180808-ubuntu-18.04.1-desktop-amd64-v4.18.rc8.iso

and how to run fan? i have unlock bios
thanx

**Comment by stockmind** [comment]
Use the `update-kernel.sh` script of this repository to update to latest Hans kernel, then run `update.sh` script to fix any issue.
I'm sorry I was very busy lately and hadn't time to keep up with updates and issues.
