### ISSUE TITLE
gpdfand problem

### ISSUE THREAD

**Issue by cselti** [stockmind/gpd-pocket-ubuntu-respin#127]
I'm have installed Linuxmint 18.3 Cinnamon version with gpd pocket patches (from the image gpdpocket-20180306-4.16.0-rc3-linuxmint-18.3-cinnamon-64bit.iso). I have updated to the latest ubuntu-respin version, and I have tried several patched kernel version, but the gpdfand has always exited with following error:

```
sudo gpdfand 
Traceback (most recent call last):
  File "/usr/local/sbin/gpdfand", line 63, in <module>
    init()
  File "/usr/local/sbin/gpdfand", line 60, in init
    gpio_export.write(unicode(id))
IOError: [Errno 16] Device or resource busy
```
I have tried some respinned live image (like gpdpocket-gnome-20180808-ubuntu-18.04.1-desktop-amd64-v4.18.rc8.iso) but the gpdfand always exits with that error.

My problem-reporting.sh output is the following:
```
**Kernel:** 4.18.0-rc7-custom-matlala-03-08-2018
**Desktop Environment:** 
**Display:** :0
**Login:** ExecStart=/usr/sbin/lightdm
**Monitor:** DSI1 connected primary 1920x1200+0+0 right (normal left inverted right x axis y axis) 0mm x 0mm
**Scripts:**  gpdfand gpdscreen gpdscreen-indicator
**EFI:**  [ 0.000000] efi: EFI v2.40 by American Megatrends
**EFI**  Release Date: 08/07/2017
```
What I have been doing wrong?
Thank you all in advance,
Adrian

**Comment by stockmind** [comment]
https://github.com/stockmind/gpd-pocket-ubuntu-respin/blob/master/README.md#gpd-fan-daemon-fail-to-run

**Comment by cselti** [comment]
Thanks!
I haven't read it properly - I put that module on blacklist and the gpdfand works properly :)

**Comment by adiif1** [comment]
U put gpd_pocket_fan to blacklist?

**Comment by cselti** [comment]
> U put gpd_pocket_fan to blacklist?

Yes, because the gpdfand python daemon works better for me.
