### ISSUE TITLE
Bad TransformationMatrix breaks mouse capture in many apps/games

### ISSUE THREAD

**Issue by mallardtheduck** [stockmind/gpd-pocket-ubuntu-respin#128]
In 40-trackpoint.conf there is a line:

Option "TransformationMatrix" "2 0 0 0 2 0 0 0 1"

I'm not sure what this was intended to do, but on my system (18.04.1 Xubuntu) this causes many programs that attempt to "capture" the mouse to malfunction (the mouse is "stuck" in the bottom right corner). This affects many common applications including Qemu, VirtualBox and most (all?) games that use SDL2.

Setting the 2s back to 1s or removing the line completely appears to have no ill effects. Note that this Option TransformationMatrix is "inherited" by any USB pointing device plugged in, it doesn't just affect the "nub".

It took me **_a lot_** of troubleshooting and frustration to find the cause of this issue, not helped by the fact that the symptoms are the same/similar to an SDL bug from 5-10 years ago, so if this can be fixed to avoid problems for anybody else (or me when I inevitably re-install and can't remember the fix...), that would be great...

**Comment by stockmind** [comment]
Hi!

I'm sorry for your issues and frustration, if i remember correctly that change was done to improve the pointer speed on trackpoint, but as you noticed this will be inherited by other pointing devices too

I wasn't aware this would also create such a mess with other applications and i agree with you that is better to remove it
