### ISSUE TITLE
GPD Official Ubuntu firmware available

### ISSUE THREAD

**Issue by derjohn** [stockmind/gpd-pocket-ubuntu-respin#13]
Hello,
maybe we shoud mention that GPD now has an own ubuntu image. Furthermore we should look in der kernel config  drivers?

rgds,
j

====

Dear Backer

    Here is the download link of the beta version of Ubuntu,  We hope senior  Linux users can help us to test it, Just report the bug to us,We will collect all of information to make the final firmware of Ubuntu better.  And for the person who not much familiar with Linux, please don't participate this test. We are wondering some unpredictable issue appears.

https://mega.nz/#!EQwUHTCC!3Qsf8UQxbAKiHzFSxwxVVjaw7Bq_boeo6Bk8IF5nZ7U

Millions of thanks. Have a nice day !

GPD team

Best regards

**Comment by stockmind** [comment]
I'm returning home right now braming to test It out ASAP.

Il 27 lug 2017 21:12, "derjohn" <notifications@github.com> ha scritto:

**Comment by stockmind** [comment]
System uploaded by GPD is corrupted. Installer crash on start.
Live environment use kernel 4.4.0-31-generic. Squash fs contains also files related to 4.12-rc2 kernel.
No audio, no mic on live.
Rotation doesn't work. Black screen after xrandr rotation or using system dialog to rotate display. This may be due to the kernel version.
I'm investigating on files added by GPD.

**Comment by derjohn** [comment]
Sounds like a good job GPD did. Not. Might the image be corrupted due to mega download issues? Tried again?

**Comment by stockmind** [comment]
Here a diff from files of vanilla Ubuntu 16.04.1 image and GPD official firmware beta.
http://ge.tt/8sh4Myl2

Better highlight:
https://pastebin.com/B2aasxVx

In green files that are added/different in GPD firmware.
In red files of vanilla Ubuntu image.

**Comment by stockmind** [comment]
They added files for wifi and audio as we do with respin and ansible playbook:
    
    /usr/share/alsa/ucm/chtrt5645/HiFi.conf
    /usr/share/alsa/ucm/chtrt5645/chtrt5645.conf

    /lib/firmware/brcm/brcmfmac4356-pcie.txt


Audio files are the same, wifi pcie txt instead is different.
Here the diff: https://www.diffchecker.com/5Rp67yNs
In red their file, in green our file.

Then there is:

    /etc/acpi/lm_lid.sh
    /etc/acpi/events/lid

That are new scripts related to closing/opening lid.

    /etc/acpi/lm_lid.sh

    #!/bin/sh
    case $(cat /proc/acpi/button/lid/LID0/state | awk '{print $2}') in
    closed) sudo echo mem > /sys/power/state;;
    open) vbetool dmps on;;
    esac



    /etc/acpi/events/lid

    event=button/lid
    action=/etc/acpi/lm_lid.sh

No daemon or script that directly handle the fan. It could be due to the BIOS update that turn on fan on boot.
GPD firmware is probably using above script to turn on and off the fan when lid is closed or open.

Content of rc.local:

    echo disabled > /sys/bus/usb/devices/usb1/1-2/power/wakeup
    echo 1500000  > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
    echo 1500000  > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq
    echo 1500000  > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq
    echo 1500000  > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq
    exit 0

And in /etc/systemd/logind.conf

    HandleLidSwitch=ignore

**Comment by cawilliamson** [comment]
Awesome work here man - I can't believe what utter douchebags GPD are being here.

I really need to grab a copy of this kernel and find out if it's basically Hans's kernel sources - that would be ridiculously cheeky considering they refused to send him a GPD Pocket to dev with - completely ignored him and then released this absolute garbage. I really don't understand business sometimes.

"NO! We would rather look like UTTER fools than sacrifice a £300 device!!"

Very strange.

**Comment by scofieldpeng** [comment]
@stockmind https://pan.baidu.com/s/1bKegoe the gpd company release the new iso, but the f**k baidu netdisk limit the download rate, so u may take a long time to download

**Comment by stockmind** [comment]
https://www.reddit.com/r/GPDPocket/comments/70qdsp/diff_of_latest_gpd_official_ubuntu_firmware_iso/?st=j7pa5css&sh=02dc3f67

Diff of latest ubuntu image with files extracted!
http://ge.tt/4t7qsZm2

**Comment by sigboe** [comment]
@stockmind I went into a website I think is an [official Chinese version of the GPD site](http://www.softwincn.com/). Found it googling a representative of GPD on his/hers twitter.

So I saw some promo stuff about Ubuntu there, clicked it but just opened the thumbnail in a new tab, but was able to figure out where the link was supposed to point to. [A post on Baidu](http://tieba.baidu.com/p/5310315871). Looks like its posted by a GPD employee, by the handle of (google translates into) GPD Handsome Fox. The post is not so interesting only talks about updating your official GPD ubuntu image to a newer official one. But it links to a FAQ (thanks Google translate)

[Ubuntu firmware FAQ solution](http://tieba.baidu.com/p/5274599209) this post is called. By a user with GPD logo in his/hers avatar. Talks about fixing issues with linux on the GPD. Lo and behold, he suggests installing git, pulling your repo, and running update.sh. 

Not saying this as necessarily negative, I just thought it was interesting to know for you.

**Comment by sigboe** [comment]
@jwrdegoede also this here is possibly the kernel source for the official image? https://github.com/253647445/Pocket-Ubuntu-kernel just reading further in the baidu thread.

**Comment by huangtao00** [comment]
Do not  expect the GPD company to do more. It is really a little startup. I believe all the guys here can do it better than GPD company. As  a Chinese, I always try to tell all the updates here to the GPD official through QQ group which is a very popular app in China.  One more thing, I found the GPD company knows nothing about how the open source project works.
