### ISSUE TITLE
Power button pulses orange when system is in use

### ISSUE THREAD

**Issue by maxengel** [stockmind/gpd-pocket-ubuntu-respin#14]
The power button continues to pulse orange after a successful boot.

**Comment by stockmind** [comment]
Kernel used?

**Comment by maxengel** [comment]
I used the kernel built via the process documented in the readme. I did note my process in #11.

**Comment by stockmind** [comment]
Charger is not connected? On 4.13-rc2 kernel that i've compiled that doesn't seems to happen.

**Comment by maxengel** [comment]
This happens when the charger is not connected. It also happens with the repspun Ubuntu 17.04 image.

**Comment by kanocz** [comment]
for me on `4.13-rc2` it pulses only when charger is connected

**Comment by maxengel** [comment]
@kanocz: are you using the kernel provided via the download or did you build your own? I built my own, so that could be the issue. My kernel is 4.12-rc7-custom. I upgraded to 4.13.0-041300rc2-generic via [ukuu](http://www.teejeetech.in/p/ukuu-kernel-upgrade-utility.html) and still had in happening. Also, the battery/charging indicator disappeared after updating the kernel.

**Comment by kanocz** [comment]
@maxengel I'm using downloaded kernel yet

**Comment by stockmind** [comment]
Kernel 4.13 is not stable, should use RC7 for good scaling frequency and better management.
I close this at the moment as should be a temporary issue due to latest kernel commits. RC3 is out and i'm waiting for a better connection to try a new build more "vanilla".

**Comment by maxengel** [comment]
As mentioned this happened for me with RC7 and RC2...

**Comment by maxengel** [comment]
This happens as soon as the system boots. I guess it is either a BIOS issue or something with my system?
