### ISSUE TITLE
Windows manager performance seems degraded

### ISSUE THREAD

**Issue by maxengel** [stockmind/gpd-pocket-ubuntu-respin#17]
With elementary OS, I've noticed that window re-positioning is jerky. In addition, graphics in general seem less smooth (animation when opening/closing apps, resizing windows,etc.).

**Comment by stockmind** [comment]
That's seems related to GNOME/Pantheon way to handle vsync and video.
Other DE like KDE works better but with some occasioanal graphic glitch. That could be related to the DRI and intel driver that hopefully will be updated.
Once modesetting video driver will fix rotation tear problem we could switch to it as it's more stable.
