### ISSUE TITLE
Wake from sleep has graphical issue on elementary OS

### ISSUE THREAD

**Issue by maxengel** [stockmind/gpd-pocket-ubuntu-respin#18]
When opening the lid, the password/login screen is rotated back 270 degrees, although it reverts when I login after sleep to the correctly rotated orientation.

**Comment by stockmind** [comment]
I was working in getting that fixed. Just need to check how Pantheon handle things.

**Comment by stockmind** [comment]
Should be fixed on latest commit. Pull changes and update for wayland.

**Comment by maxengel** [comment]
Touch input seems fine, but the login screen is still rotated.

**Comment by stockmind** [comment]
Post result of

    xrandr -q

Maybe also LCD matching is different.

**Comment by stockmind** [comment]
Ubuntu iso is working correctly for you? Rotation is ok?

**Comment by stockmind** [comment]
Just tested latest bios, update grub options and text will be ok.
Login should be rotated correcty on first boot and after closing and reopening lid. 
It still have wrong rotation on lock or suspend because that doesn't seems to trigger the script.
I will check display tomorrow if i have some time.

**Comment by stockmind** [comment]
Be sure to pull latest git on master branch and be sure to use this to update:

    sudo ./update.sh wayland

**Comment by maxengel** [comment]
The only issue now is login after logout/sleep/lid closed (if sleep and opening the lid requires a password).

typed on a touchscreen...

**Comment by stockmind** [comment]
Only logout/suspend give me problems. Closing lid is good on mine! I should do more tests!
