### ISSUE TITLE
Touch input is not rotated in elementary OS

### ISSUE THREAD

**Issue by maxengel** [stockmind/gpd-pocket-ubuntu-respin#19]
While touch input does work, it isn't rotatated, so tapping the left side of the screen manipulates the top bar.

**Comment by stockmind** [comment]
That's related to rotation and handle of scripts After sleep that needs to
Be fixed. I'm working on It It Will Be fixed when i find a way to handle
evrything in pantheon :)

Il 28 lug 2017 21:12, "max engel" <notifications@github.com> ha scritto:

**Comment by stockmind** [comment]
Delete your actual monitors file:

    rm ~/.config/monitors.xml

Run update script

    sudo apt-get install -y git
    git clone https://github.com/stockmind/gpd-pocket-ubuntu-respin.git
    cd gpd-pocket-ubuntu-respin/
    chmod +x update.sh
    sudo ./update.sh wayland
    cp display/monitors_wayland.xml ~/.config/monitors.xml

Use root user only for update.sh script, for everything else use your default user.
Let me know.

**Comment by stockmind** [comment]
Display on login could still be in wrong rotation but everything else should be fine.

**Comment by maxengel** [comment]
Display is still rotated on login. Would you like me to file that as a separate issue?

**Comment by stockmind** [comment]
As i expected! we already have that issue open #18 
I still don't know why it ignores monitors file on wake or rotation...
I've also disabled animation for pantheon and Gnome for better user experience.
It should be better now.
If touch is ok i close this.

**Comment by maxengel** [comment]
What effect does animation add to the experience? I'm not sure what is animated...

typed on a touchscreen...

**Comment by stockmind** [comment]
Animations related to menu showing, window minimizing/closing, that sort of fancy stuff that you usually don't notice. They slow down opening of things and scrolling on menus.

Update again, i should have fixed rotation after sleep and on login. Let me know.

**Comment by maxengel** [comment]
Do you think with newer driversbyou'll be able to restore them? I like the fancy stuff ;-)

**Comment by stockmind** [comment]
Whenever we get better intel driver support, yes

**Comment by maxengel** [comment]
This seems to have somehow changed the placement of the battery indicator (see attached). The icon is moved left, but the menu seems to be in the right place.
![screenshot from 2017-07-30 13-08-21](https://user-images.githubusercontent.com/810989/28755410-44de318e-7528-11e7-98a5-c757b22f8109.png)
