### ISSUE TITLE
Remove 'fbcon=rotate:1'

### ISSUE THREAD

**Issue by cawilliamson** [stockmind/gpd-pocket-ubuntu-respin#2]
Hey there!

Firstly - awesome work on this project and thanks for the shout out! 👍 

Just wanted to let you know - you no longer need 'fbcon=rotate:1' - Hans managed to remove that need from his rc7+ kernels. :)

I'm still unsure about i915.fastboot=1 being needed - will confirm shortly.

One question I do have - do you have any audio stuttering with your setup? That's one issue I'm still facing.

Thanks!

**Comment by stockmind** [comment]
Thanks for the advice! :) 

Stuttering no, but i sometimes get those crackling noise on high volume that is annoying.
Also it seems that respinned ISO with GNOME or KDE don't recognize the audio output device on boot.
The Ubuntu Unity works well instead.

I need to update the Ubuntu Unity ISO with latest kernel and do some more test.

What DE are you using?

I've just noticed that "pure" GNOME 3 as DE is "slow" compared to Unity, KDE or anything else. It hang a little on some common task like drag and drop windows or write on terminal and call commands with tab or simple tasks like that. Audio may be affected.

It does this with and without the modesetting video driver. 
I don't know if might be related to different compositor way to work.
But it's also the only DE that don't give me tearing if i use the modesetting driver.

I need to use intel driver  to get no tearing on any other DE.

This should be related to the rotation of display that on modesetting driver affect the composition and the tear-free support of the driver.
