### ISSUE TITLE
"Double" battery on 4.13.0-rc2-custom-2

### ISSUE THREAD

**Issue by kanocz** [stockmind/gpd-pocket-ubuntu-respin#20]
On 4.12 it was only one (right way), but on `4.13.0-rc2-custom-2` I see one more (something like "usb-c-adapter" with 0% charged)

**Comment by stockmind** [comment]
Are you using Unity? Will check this. Could be the ongoing usb C charger fix that are work in progress.

**Comment by kanocz** [comment]
Yes, Unity from your ISO
Also made a try with KDE Neon, live with `4.13.0-rc2-custom-2` also has the same issue

**Comment by stockmind** [comment]
I suggest to return to 4.12 RC7 as it seems that 4.13 rc2 doesn't handle frequency of processor right.
This also fix the issue about double battery!
