### ISSUE TITLE
No info how to update BIOS

### ISSUE THREAD

**Issue by kanocz** [stockmind/gpd-pocket-ubuntu-respin#26]
It's link to special BIOS for linux, but in this package only Windows binary for flashing can be found.
adding some instructions how to flash from Linux or UEFI shell will be great!
P.S.: cat https://downloadcenter.intel.com/download/18317/BIOS-Firmware-Update-Configuration-Utilities-for-Windows-Linux-WinPE-UEFI be used?

**Comment by stockmind** [comment]
There are some working instruction on Facebook group page and Reddit, will report those ASAP.

**Comment by stockmind** [comment]
Adapt this to latest bios. You should use flashrom package from repository.

    First "flashrom -p internal -r backup.bin "and then "flashrom -p internal -w Rom_8MB_Tablet.bin" as root.

Look at this:

https://www.reddit.com/r/GPDPocket/comments/6q74en/unlocked_gpd_pocket_bios/

Do not shoutdown device until you can get a complete flash. If you want to try and write some steps feel free to make a pull request for BIOS section! Thanks!

**Comment by maxengel** [comment]
To clarify, this BIOS is newer than the 05/07 one?

If so, and it performs better, I can add it to the readme.

**Comment by kanocz** [comment]
@maxengel I can test this on Tuesday, but not expect any changes

**Comment by maxengel** [comment]
thanks @kanocz. I'm just going to give it a go on my system, and will have a pull request in shortly for updated documentation.

**Comment by maxengel** [comment]
This is ready in my latest pull request

**Comment by maxengel** [comment]
We should be able to close this out now.

**Comment by stockmind** [comment]
You did a great job on docs!
