### ISSUE TITLE
Build script errors.

### ISSUE THREAD

**Issue by sweisman** [stockmind/gpd-pocket-ubuntu-respin#27]
Just did a refresh to do a new respin and am getting these errors:

[sweisman@gorilla gpd-pocket-ubuntu-respin]$ PATH=/usr/sbin:/sbin:/bin:$PATH ./build.sh /site/media/ubuntu-17.04-desktop-amd64.iso 
Display setting: Xorg
rm: cannot remove 'isorespin.log': No such file or directory
rm: cannot remove 'linuxium-*': No such file or directory
rm: cannot remove 'linux-*.deb': No such file or directory
./build.sh: line 75: unexpected EOF while looking for matching `"'
./build.sh: line 80: syntax error: unexpected end of file

**Comment by stockmind** [comment]
Ops, fixed. 
Pull latest commit and retry.
