### ISSUE TITLE
Fan keeps running while system is asleep and charging

### ISSUE THREAD

**Issue by maxengel** [stockmind/gpd-pocket-ubuntu-respin#28]
On the [05/07 BIOS](http://www.gpd.hk/news.asp?id=1519&selectclassid=002002) with elementary OS respin, my fan keeps running when the lid is shut and the system should be asleep.

**Comment by stockmind** [comment]
Fan is also on when not charging and lid closed?

**Comment by maxengel** [comment]
Yes, should I try on the later BIOS?

**Comment by Maokei** [comment]
I have the same issue with unity, but isn't this more a bios i issue than anything else?

**Comment by stockmind** [comment]
Probably. I will integrate gpd scripts for sleep so It Will work with
latest BIOS.

Il 31 lug 2017 9:59 AM, "Rickard" <notifications@github.com> ha scritto:

**Comment by stockmind** [comment]
What kernel are you using? Try 4.12 RC7.
Be sure to boot from right kernel.
On my  GPD Unity sleep works as expected on latest BIOS with and without charger inserted.
