### ISSUE TITLE
Build.sh missing kernel link

### ISSUE THREAD

**Issue by maxengel** [stockmind/gpd-pocket-ubuntu-respin#32]
I just tried build.sh, but it didn't provide the download link. The output reports an error on line 48.

**Comment by stockmind** [comment]
Could you post the error? I will add an argument to force print of the
link.

Il 01 ago 2017 07:55, "Max Engel" <notifications@github.com> ha scritto:

**Comment by mishan** [comment]
See pr #34

**Comment by stockmind** [comment]
Thanks, sorry my bad!
