### ISSUE TITLE
Kernel 4.12.3 from new Arch iso release

### ISSUE THREAD

**Issue by microdou** [stockmind/gpd-pocket-ubuntu-respin#33]
The latest arch linux `2017.08.01` iso containing kernel `4.12.3` is out. Does it mean we don't need customized/hacked kernel anymore for arch installation?

**Comment by stockmind** [comment]
Lot of needed patches have landed officially on 4.13. 
You can try and report if that kernel works good!

**Comment by cawilliamson** [comment]
@microdou 4.12.3 != 4.13 - there are a lot of patches which wont land at all until 4.13 so no - you're likely to still need a hans-patched kernel until then. :)

**Comment by microdou** [comment]
@stockmind @cawilliamson Thanks!
