### ISSUE TITLE
Unable to respin Debian ISO

### ISSUE THREAD

**Issue by mishan** [stockmind/gpd-pocket-ubuntu-respin#35]
`./isorespin.sh: '/home/mnasledov/src/gpd-pocket-ubuntu-respin/debian-testing-amd64-DVD-1.iso' must be an Ubuntu (or Ubuntu flavour), Linux Mint, elementary, or neon desktop ISO.`

The project description / README says Debian is supported -- if that's not the case, the docs should be updated to be clear.

**Comment by stockmind** [comment]
Ian has just removed Debian and Kali Linux support for compatibility, usefulness, security and other reasons. This is pushing me to try a different approach for respins.. I'm just in talk with him. Will update when I have news about that.

**Comment by RevoltsRevolution** [comment]
Any news? I'm trying for days to get kali to work, now I see your response :/

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by stockmind** [comment]
Checkout the cawilliamson work, he just wrote a different script to handle ISO of different distros including Kali: https://github.com/cawilliamson/ansible-gpdpocket/

**Comment by RevoltsRevolution** [comment]
I did... And wrote in the thread. I only get errors at the end :/ I'm not the best in linux, so it's hard for me to constantly solve error a) to get to error b) and then c)... This is why I was hopeing for your solution :/ I wish there was just a program to drag the iso in and get a magical iso out or something ;)

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by stockmind** [comment]
Ian has just added support for BackBox that is an alternative to Kali. You
can try a respin of that. You have only to delete isorespin.sh script from
my repo and try to build that iso.

Il 12 ago 2017 22:45, "RevoltsRevolution" <notifications@github.com> ha
scritto:
