### ISSUE TITLE
elementary OS now missing battery indicator

### ISSUE THREAD

**Issue by maxengel** [stockmind/gpd-pocket-ubuntu-respin#36]
While the changes made have caused most elementary/Pantheon-related issues to be solved, something changed (perhaps in build.sh) that now has the battery indicator hidden in the top bar. In addition, the drop-down menus from the other indicators no longer align correctly.

**Comment by stockmind** [comment]
What kernel got integrated into iso? I have changed kernel version in these days. Also what BIOS are you now? have you flashed the unlocked one of 2017/06/28 ? It seems that on that BIOS battery indicator is lost.

**Comment by maxengel** [comment]
I am on the latest bios and using the kernel supplied via build.sh.

**Comment by stockmind** [comment]
Just respinned elemetary but no problem with battery indicator. ISO is fine? No corruption on original ISO?

**Comment by maxengel** [comment]
The ISO is from the latest version of Loki. Are you running it in Live mode or did a full install?

On Aug 03, 2017, at 03:36 PM, stockmind <notifications@github.com> wrote:

Just respinned elemetary but no problem with battery indicator. ISO is fine? No corruption on original ISO?

**Comment by stockmind** [comment]
Live, will try an install!

**Comment by maxengel** [comment]
Odd, my respun ISO in live mode also doesn't have the indicator either. Did you go through the exact same process as what I've put in the readme?

**Comment by stockmind** [comment]
Should be fixed on latest 4.13-rc5 kernel! Will make a new elemetary os iso with latest rotation updates.

**Comment by maxengel** [comment]
Great to hear! Is this going to merge into the other GPD Linux project, or will this eventually pick back up? I've found our process here to be more reliable in output.
