### ISSUE TITLE
Gnome un-rotates touch on sleep

### ISSUE THREAD

**Issue by kfarwell** [stockmind/gpd-pocket-ubuntu-respin#37]
I'm on Ubuntu 17.04 with Gnome 3, X11 (not Wayland... I find touch works better in X apart from this issue), Linux 4.13.0-rc2-custom-2, and the 07/05 BIOS.

I can rotate touch input to work correctly with `xinput set-prop 11 'Coordinate Transformation Matrix' 0 1 0 -1 0 1 0 0 0` but it rotates back when I close the lid and resume.

I tried putting this in a /etc/pm/sleep.d/ resume script but couldn't get it to work.

**Comment by kfarwell** [comment]
It also rotates back when the screen blanks/locks either with super-l or from Gnome's power saver timeout.

**Comment by stockmind** [comment]
Try to update installation with this:

    sudo apt-get install -y git
    git clone https://github.com/stockmind/gpd-pocket-ubuntu-respin.git
    cd gpd-pocket-ubuntu-respin/
    chmod +x update.sh
    sudo ./update.sh wayland

**Comment by kfarwell** [comment]
No luck. I tried updating with `sudo ./update wayland` as well as just `sudo ./update` (I am using X).

**Comment by stockmind** [comment]
wayland is ambigous in this case but GNOME based distros seems to match monitor configuration in a different way, even in X. Using wayland option you use a different monitors file that should work with GNOME and GNOME based DE. After launch of sudo ./update wayland you should reboot and check, have you already tried that?

**Comment by kfarwell** [comment]
Gotcha.

> After launch of sudo ./update wayland you should reboot and check, have you already tried that?

Yeah I did. No difference.

**Comment by stockmind** [comment]
Try to pull latest changes (i've tried extending waiting times for rotation) and use wayland setting.
I will anyway try a respin of GNOME and will update you !

**Comment by kfarwell** [comment]
> Try to pull latest changes (i've tried extending waiting times for rotation) and use wayland setting.

No luck.

```
git pull
sudo ./update wayland
sudo reboot
```

**Comment by stockmind** [comment]
Ok will absolutely try a respin with GNOME! Are you using Ubuntu GNOME distro or Ubuntu Unity with GNOME installed?

**Comment by kfarwell** [comment]
I started from regular Unity Ubuntu 17.04 then switched by installing the `ubuntu-gnome-desktop` package.

**Comment by stockmind** [comment]
I'm sorry, but i'm starting to have not much time to fix things and support this. Look at this project as it should work better and should be the supported one in future.

https://github.com/cawilliamson/ansible-gpdpocket

**Comment by stockmind** [comment]
Should be fixed on latest commit. Running 

    git pull
    sudo ./update gnome
    sudo reboot

Should fix the problem

**Comment by stockmind** [comment]
Download latest changes, run command above and try this:

https://github.com/stockmind/gpd-pocket-screen-indicator

Let me know.
