### ISSUE TITLE
volume hotkey can not work

### ISSUE THREAD

**Issue by scofieldpeng** [stockmind/gpd-pocket-ubuntu-respin#4]
hello, I install the ubuntu u share on the mega and i find the volume hotkeys are not work, it's there any operations i miss? do i need to run the bash script in this repo?
anyway, thanks to your iso file:)

**Comment by stockmind** [comment]
Volume keys need to be fixed. I'll look into this.

**Comment by stockmind** [comment]
Try this in a terminal:

    set-card-profile alsa_card.platform-cht-bsw-rt5645 HiFi

Test your sound hotkeys. Then append it to /etc/pulse/default.pa with

    echo "set-card-profile alsa_card.platform-cht-bsw-rt5645 HiFi" >> /etc/pulse/default.pa

Let me know

**Comment by scofieldpeng** [comment]
hello, i run the first command but the comand set-card-profile not found, is there anything i miss?

**Comment by stockmind** [comment]
Post result of this

    pacmd list-cards

**Comment by scofieldpeng** [comment]
hello, this is the result of pacmd list-cards
```
2 card(s) available.
    index: 0
	name: <alsa_card.pci-0000_00_02.0-platform-hdmi-lpe-audio>
	driver: <module-alsa-card.c>
	owner module: 6
	properties:
		alsa.card = "0"
		alsa.card_name = "Intel HDMI/DP LPE Audio"
		alsa.long_card_name = "Intel HDMI/DP LPE Audio"
		alsa.driver_name = "snd_hdmi_lpe_audio"
		device.bus_path = "pci-0000:00:02.0-platform-hdmi-lpe-audio"
		sysfs.path = "/devices/pci0000:00/0000:00:02.0/hdmi-lpe-audio/sound/card0"
		device.bus = "pci"
		device.vendor.id = "8086"
		device.vendor.name = "Intel Corporation"
		device.product.id = "22b0"
		device.product.name = "Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Configuration Registers"
		device.string = "0"
		device.description = "Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Configuration Registers"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card-pci"
	profiles:
		output:analog-stereo: Analog Stereo Output (priority 6000, available: unknown)
		off: Off (priority 0, available: unknown)
	active profile: <output:analog-stereo>
	sinks:
		alsa_output.pci-0000_00_02.0-platform-hdmi-lpe-audio.analog-stereo/#0: Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Configuration Registers Analog Stereo
	sources:
		alsa_output.pci-0000_00_02.0-platform-hdmi-lpe-audio.analog-stereo.monitor/#0: Monitor of Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Configuration Registers Analog Stereo
	ports:
		analog-output: Analog Output (priority 9900, latency offset 0 usec, available: unknown)
			properties:
				
    index: 1
	name: <alsa_card.platform-cht-bsw-rt5645>
	driver: <module-alsa-card.c>
	owner module: 7
	properties:
		alsa.card = "1"
		alsa.card_name = "chtrt5645"
		alsa.long_card_name = "AMICorporation-Defaultstring-Defaultstring-Defaultstring"
		alsa.driver_name = "snd_soc_sst_cht_bsw_rt5645"
		device.bus_path = "platform-cht-bsw-rt5645"
		sysfs.path = "/devices/pci0000:00/808622A8:00/cht-bsw-rt5645/sound/card1"
		device.string = "1"
		device.description = "chtrt5645"
		module-udev-detect.discovered = "1"
		device.icon_name = "audio-card"
	profiles:
		HiFi: Default (priority 8000, available: unknown)
		off: Off (priority 0, available: unknown)
	active profile: <HiFi>
	sinks:
		alsa_output.platform-cht-bsw-rt5645.HiFi__hw_chtrt5645__sink/#1: chtrt5645 Headphones + Speaker
	sources:
		alsa_output.platform-cht-bsw-rt5645.HiFi__hw_chtrt5645__sink.monitor/#1: Monitor of chtrt5645 Headphones + Speaker
		alsa_input.platform-cht-bsw-rt5645.HiFi__hw_chtrt5645__source/#2: chtrt5645 Headset Microphone + Internal Digital Microphones + Internal Analog Microphones
	ports:
		[Out] Headphones: Headphones (priority 100, latency offset 0 usec, available: unknown)
			properties:
				
		[Out] Speaker: Speaker (priority 100, latency offset 0 usec, available: unknown)
			properties:
				
		[In] HSMic: Headset Microphone (priority 100, latency offset 0 usec, available: unknown)
			properties:
				
		[In] DMic: Internal Digital Microphones (priority 100, latency offset 0 usec, available: unknown)
			properties:
				
		[In] Mic: Internal Analog Microphones (priority 150, latency offset 0 usec, available: unknown)
			properties:
```

**Comment by stockmind** [comment]
My fault, just missed "pacmd" part:

    pacmd set-card-profile alsa_card.platform-cht-bsw-rt5645 HiFi

**Comment by scofieldpeng** [comment]
unfortunately, i try this command and the hotkeys are not work, then i restart the machine but get the same result, Do i need to do another operation?

**Comment by stockmind** [comment]
Try this
   
    sed -i "s/#JackControl \"Headphone Jack\"/JackControl \"Headphone Jack\"/" /usr/share/alsa/ucm/chtrt5645/HiFi.conf
    sed -i "s/#JackHWMute \"Speaker\"/JackHWMute \"Speaker\"/" /usr/share/alsa/ucm/chtrt5645/HiFi.conf
    rm ~/.config/pulse/*
    pacmd set-card-profile alsa_card.platform-cht-bsw-rt5645 HiFi

Then reboot.
Select speakers in audio system settings.
Audio keys should work.

Let me know.

**Comment by scofieldpeng** [comment]
i try and still not work

**Comment by stockmind** [comment]
I've tried to build a new iso and no problems with media keys applying tips above. Can you try to build one and test in live? I can't upload anything big with my connection right now but will update ISOs with latest updates related to gpdfand, etc.. as soon as possible. Be aware that latest kernel build could be unstable.

**Comment by scofieldpeng** [comment]
sorry to response too late, i have tried last week(2017/7/15 +0800) and the system will freeze, the kernel I use is your google dirve that you share the linke in this issue page(https://github.com/stockmind/gpd-pocket-ubuntu-respin/issues/3)
by the way, i charge rate is too slow when the machine power on, can you help me to slove this problem?tks a million:-)

**Comment by stockmind** [comment]
Be sure to select right kernel on boot. Check second grub boot option on boot and select RC7 kernel.

Regarding charging too slow:
Hans is working on it. It's related to the USB Type C port management that's still a work in progress. He know what to do, it's just a matter of some weeks to get it working correctly!

**Comment by huangtao00** [comment]
thx for the work all you have done. I will try the stable kernel.

**Comment by stockmind** [comment]
Sound keys should be fixed on latest iso and using latest update script. Previous inserted lines should be removed from default.pa file. Will try to handle that with update script.

**Comment by scofieldpeng** [comment]
i clone and update the repo, nothing work, by the way, i update the kernel to 4.13rc2 and the the status bar show two battery icon, one the empty enery and the other is full, how can I solve this kind of problem?

**Comment by ThuggishNuggets** [comment]
Running into this problem again after running the latest `update.sh` and `update-kernel.sh` from `master`. Volume hot keys were working prior to this, but I also ran software updates before that too so that might have broken it.

Anyone else having this issue again?

**Comment by z-image** [comment]
Doesn't work for me too.
