### ISSUE TITLE
Which BIOS version to go with?

### ISSUE THREAD

**Issue by timbotron** [stockmind/gpd-pocket-ubuntu-respin#41]
I'd love to use the prespun Ubuntu ISO. I have the original BIOS. Should I upgrade to latest bios version? Or he second one, which sounds less buggy? Thanks in advance. :)

**Comment by stockmind** [comment]
BIOS version ATM doens't seems to bring lot stability fixes.
On latest BIOS you will have fan running while charging that could be a good thing!

About Ubuntu respun my latest ISO is stable but i can suggest you to try an iso builded using cawilliamson work.
It should work better and should be the supported one in future.

https://github.com/cawilliamson/ansible-gpdpocket

**Comment by cawilliamson** [comment]
The unlocked BIOS is great but sadly (currently - Hans is working on this) battery monitoring is broken.

This, however, is likely to be fixed within the next few days and that appears to be the only major problem. My advice would be remain on stock until the battery issue is fixed, then switch to the Ubuntu one if you want control and switch to the latest one if you just want it to work! :)
