### ISSUE TITLE
no sound from headphone jack

### ISSUE THREAD

**Issue by poeselt** [stockmind/gpd-pocket-ubuntu-respin#42]
i change in my audio setup from speaker to headphones(chrtr5645) and the volume is up... but still no sound

Kernel: 4.12.0-rc7-custom

**Comment by stockmind** [comment]
Hello, this has been fixed on latest kernel: https://drive.google.com/open?id=0B8-M0eiR7v8sTlJMU01DMm1ZOW8

Extract this in a folder and run 

    dpkg -i *.deb 

To install.
Be sure to boot with that kernel. After you boot you can see a new battery icon related to USB Type C charger, Hans is working on fixing it, it's just aesthetic.

**Comment by poeselt** [comment]
you are right,- thx for your help
