### ISSUE TITLE
Use highest temperature core to determine fan speed

### ISSUE THREAD

**Issue by Redsandro** [stockmind/gpd-pocket-ubuntu-respin#45]
Since single core running tasks can take one core up in temperature considerably compared to the rest, and since Atom Z8750 has a single core burst mode of 2.5 GHz, perhaps it's better to use the core with the highest temperature rather than the average.

Currently, [`gpdfand.py:39`](https://github.com/stockmind/gpd-pocket-ubuntu-respin/blob/master/fan/gpdfand.py#L39):

```
    if(len(temps) > 0): 	
        return sum(temps) / float(len(temps))
```

Should be e.g.:

```
    if(len(temps) > 0): 	
        return max(temps)
```

Upstream PR: https://github.com/efluffy/gpdfand/pull/6
Upstream issue: https://github.com/efluffy/gpdfand/issues/5

**Comment by stockmind** [comment]
Thanks for your suggestion and nice find! 
I report this to @cawilliamson as the rewrite in Python was done by him so he can also update it in his repo.
