### ISSUE TITLE
Raise fan temperature settings

### ISSUE THREAD

**Issue by Redsandro** [stockmind/gpd-pocket-ubuntu-respin#46]
The temperatures in [gpdfand.py](https://github.com/stockmind/gpd-pocket-ubuntu-respin/blob/master/fan/gpdfand.py) are set to low: `45`, med: `55`, high: `65`. Turbo is shut off at `60`.

Are these settings an educated guess, or something for a good reason?

Because the Thermal Junction of the [Intel Atom x7-Z8750](https://ark.intel.com/nl/products/93362/Intel-Atom-x7-Z8750-Processor-2M-Cache-up-to-2_56-GHz) is 90 degrees, I propose:

1. Use core with highest temperature for accuracy: https://github.com/stockmind/gpd-pocket-ubuntu-respin/issues/45
2. Raise limits to low: `55`, med: `65`, high: `75`, turbo off: `80`.

The CPU will clock itself down above `85` degrees.

**Comment by stockmind** [comment]
On older kernels it seems that there were some strange system freeze on temps over 65/67 degree.
Didn't try on latest kernels. Maybe it's been fixed thanks to all the new patches all around.
The temps suggested are ok on your configuration?
Can you do some stress tests and report your kernel version?
Try to get your unit as hot as you can (safely of course) and see if it hangs if you can.
I will try also in the next few days.

Thanks!

**Comment by stockmind** [comment]
I'm compiling latest kernel on GPD using your suggested temps configuration on 4.13-rc3. System seems stable and no hangs so far.
Need to test with some GFX heavy task.

**Comment by Redsandro** [comment]
Can you recommend some stress test tools? I'm having difficulties getting the GPD above 70 degrees.
The proposition was theoretical based on the factory datasheet, but if some GPDs shut down at 65 degrees, that's a problem of course.

Mine seems fine at 70 degrees.

**Please note** that at these temperatures, the cooling should activate based on the hottest temperature, not on the average temperature, as in #45.

**Comment by stockmind** [comment]
Fixed default values! System seems stable and it could be good to save some battery juice on low temps as the fan would be off.

**Comment by Redsandro** [comment]
Sounds good! :+1: 
Note that I haven't tested this above 71 degrees. Although good for real world usage, it's bad for testing. I haven't gotten the temperature higher. 

---

Unrelated to `gpdfand` but related to testing; I think I have botched some BIOS settings because my CPU won't go higher than 1440 MHz. 

Can you verify using Conky or other means (see below) that your CPU actually does go up to 1600 MHz?

```
while true; do cat /proc/cpuinfo | grep -i "cpu MHz"; sleep 1; done
```

**Comment by stockmind** [comment]
/proc/cpuinfo seems currently broken as the functions and the way frequencies are collected for intel i915 are changed on kernel side on 4.13.
Use this to check your frequencies:

    cat /sys/bus/cpu/devices/cpu*/cpufreq/scaling_cur_freq

**Comment by Redsandro** [comment]
Checked this location, same conclusion:

> $ cat /sys/bus/cpu/devices/cpu*/cpufreq/scaling_cur_freq
> 1439941
> 1439941
> 1439941
> 1439941
