### ISSUE TITLE
4.13rc7 came out - update the prebuild kernel? 

### ISSUE THREAD

**Issue by derjohn** [stockmind/gpd-pocket-ubuntu-respin#47]
... no idea if rc6 or rc7 have relavent changes fpr GPD, but for sure general stuff we shouldnt miss.

**Comment by stockmind** [comment]
I will update iso tonight! :)

Il 28 ago 2017 13:41, "derjohn" <notifications@github.com> ha scritto:

**Comment by stockmind** [comment]
I have to change my statement. I want to do some test before upload an updated iso with new kernel, i've seen that Hans didn't merged yet latest commits on master branch so maybe something is still work in progress!

**Comment by derjohn** [comment]
4.13.0 ist released - all in?

**Comment by stockmind** [comment]
I'm updating kernel to latest Hans release. USB C data seems to work on latest kernel! :) Will update once done.

**Comment by stockmind** [comment]
Updated kernel:
https://bitbucket.org/simone_nunzi/gpdpocket-kernel/downloads/gpdpocket-20170921-kernel-files.zip

You can install it using update_kernel.sh script here
https://github.com/stockmind/gpd-pocket-ubuntu-respin/blob/master/update-kernel.sh

Iso are on their way, i need to fix just one more thing on the indicator

**Comment by leledumbo** [comment]
> USB C data seems to work on latest kernel! :)

Great info! I know buying a hub is a worthy investment!

**Comment by stockmind** [comment]
Sure, it seems that also the mainline 4.13 has support for USB Type C data so it may be worth a try. Kernel support is almost fine in mainline it seems.

**Comment by kanocz** [comment]
USB-C data works find, but USB-C video doesn't work at all (tried 2 different USB-C monitors) with no messages in dmesg
