### ISSUE TITLE
screen rotation is set to normal after using the HDMI port

### ISSUE THREAD

**Issue by StefanReuscher** [stockmind/gpd-pocket-ubuntu-respin#48]
Exactly as it says in the title. After using the HDMI port with a second monitor the Pocket display is rotated to "normal" which in this case means top of the desktop is on the left screen edge.

There is some other odd behaviour with the second screen as well, such as scaling corrctly and automatic recognition, but the rotation issue is the worst.

Forgot to to mention this was with the pre-spun ubuntu image found in the downloads section.

**Comment by stockmind** [comment]
Desktop environment used and distro used?

Il 29 ago 2017 01:13, "Stefan Reuscher" <notifications@github.com> ha
scritto:

**Comment by StefanReuscher** [comment]
I used the pre-made image from the download section on the front page of this repo. Should be stock  ubuntu 17.04 with unity

**Comment by stockmind** [comment]
Do you insert HDMI cable before boot or after boot? Are you using the 20170819 image? 
Can you try to fiddle around with the Display settings and see if you can rotate the display manually?
I'll look into this

**Comment by StefanReuscher** [comment]
7I tested a typical "give a presentation" situation. Boot into Ubuntu, open your .ppt file and connect the monitor via mini hdmi-to-VGA adapter. That works out ok, although the monitor is not recognized right away. Not really a problem.
Once I remove the cable though the Pocket's monitor will reverse to the wrong rotation. If you are lucky enough and the option window is still visible you can set the rotation back to clockwise? and everything is good again.

Thanks your work.

**Comment by stockmind** [comment]
Could you try to update install looking at update section?
If screen keep rotating back to normal could you try to issue "gpdtouch" in a terminal?

**Comment by StefanReuscher** [comment]
running update.sh did not help.

running gpdtouch returns

stefan@stefan-gpdpocket:~/gpd-pocket-ubuntu-respin$ gpdtouch
right
right
right

when the screen is in correct orientation and

stefan@stefan-gpdpocket:~/gpd-pocket-ubuntu-respin$ gpdtouch
(norma
right
right

when the screen is rotated after unplugging a monitor. Running gpdtouch also fixes the screen orientation.

**Comment by stockmind** [comment]
Pull latest changes, run update-kernel.sh, run update.sh

Then donwload and install this.
Play with it and let me know.
https://github.com/stockmind/gpd-pocket-screen-indicator
