### ISSUE TITLE
Touchscreen stops working when opening the lid

### ISSUE THREAD

**Issue by sanenr9** [stockmind/gpd-pocket-ubuntu-respin#49]
Hi,

i did the respin of the kubuntu iso for the gpd pocket and it works awesome, much better then the 100% fan running on the standard ubuntu it came with :+1: 
But sometimes when i open the pocket the touchscreen stops working.
Until now i was only able to get it running again through restart.

Is there any trick or a script that i can use to restart the input device? Thanks for help

**Comment by stockmind** [comment]
I'm working on an update that should help fix this!

**Comment by stockmind** [comment]
Pull latest changes from repository and run

    sudo ./update.sh

Then install this and try it.
Let me know
https://github.com/stockmind/gpd-pocket-screen-indicator
