### ISSUE TITLE
Is there a way to update the image without reinstalling?

### ISSUE THREAD

**Issue by snazzybunny** [stockmind/gpd-pocket-ubuntu-respin#5]
I have installed ubuntu with your image and I see there's been upgrades to gpdfand. Is there something which we can run to update to the latest changes or something on those lines? Thanks.

**Comment by stockmind** [comment]
I'm working on an update script that will clean and install latest files that normally get integrated into ISO!

**Comment by stockmind** [comment]
GPD Fan daemon update istruction added to doc.
I need to add istruction for audio, grub and display.

**Comment by maxengel** [comment]
Is there a way to create a repo to handle the updates?

**Comment by stockmind** [comment]
I've just updated the README with instruction to run an Update script to keep system updated! :)
