### ISSUE TITLE
respin linuxmint18.2 issues

### ISSUE THREAD

**Issue by KeyHui** [stockmind/gpd-pocket-ubuntu-respin#52]
cannot hibernat when the lid is close
cannot suspend when the lid is close
cannot wake when the lid is reopen
charge is slow

**Comment by stockmind** [comment]
Right, i should add hibernate to the things not supported.
Suspend and wake should work, are you using Cinnamon?
Charge should be good, can you post kernel version used?

**Comment by KeyHui** [comment]
@stockmind yes, I use linuxmint cinnamon. cannot suspend or hibernate automatically when lid is close.
kernel is 4.13-rc5
and then I found the linuxmint system can break down when I watch video in bilibili etc in sometime. 
And I tested suspend is good in ubuntu 16.04 and 17.04 . but hibernate also cannot be use

**Comment by stockmind** [comment]
Hibernate is not yet supported by kernel.
With "break down" you mean kernel panic, hangs, system stuck?
Youtube also break your system?
What BIOS version have you? GPD is hot when it hangs?
Do you have same problems on video streaming on Ubuntu 17.04? Can you provide me a link to a video that give you problems? Thanks

**Comment by KeyHui** [comment]
@stockmind
yes I mean hangs, need to reboot. it happen sometime in linuxmint. I cannot make sure which video.
BIOS is 2017/06/28 BIOS for Ubuntu.
I did not find problem on Ubuntu 17.04 until now.
And I found linuxmint v18.2 smoother than ubuntu 16.04 (ubuntu-16.04.1-desktop-amd_0809_2.iso).
but ubuntu 16.04 drives better than linuxmint v18.2

**Comment by stockmind** [comment]
GNOME based Desktop Environment like Cinnamon are tricky to handle. 
Performance aren't that good and i can confirm that on GNOME i get sometimes hangs for unclear reasons. If i switch to a different tty system works, so is just X that hangs.
I can suggest you to stick to Unity, XFCE, LXQT, KDE or DE like those as they are pretty fast and stable at the moment.
