### ISSUE TITLE
How to upgrade The Linux Kernel to v4.13 release

### ISSUE THREAD

**Issue by KeyHui** [stockmind/gpd-pocket-ubuntu-respin#54]
How to upgrade The Linux Kernel to v4.13 release?
and change Kernel which you want?

**Comment by stockmind** [comment]
What kernel have you installed right now?
You can switch from one kernel to another by Grub on boot. Select "Aternative boot methods" for your distribution.

**Comment by KeyHui** [comment]
@stockmind I use 4.13-rc5 , I want to switch 4.13 stable

**Comment by stockmind** [comment]
Kernel will be updated when everything seems more stable and polished. 
On new kernel versions touch seems less stable. Need to verify this.
Kernel 4.13-rc5 is stable and works well. 
If you still have your reasons to install a new kernel you can follow the instruction here:
https://github.com/stockmind/gpd-pocket-ubuntu-respin#option-2-build-your-own-kernel
Change the kernel branch to something new like drm-intel-next-queued and run command to build.
