### ISSUE TITLE
linuxmint use external screen cannot setting dpi

### ISSUE THREAD

**Issue by KeyHui** [stockmind/gpd-pocket-ubuntu-respin#55]
linuxmint use external screen cannot setting dpi , display is so bigger

**Comment by stockmind** [comment]
I have almost finished a solution for this.

**Comment by KeyHui** [comment]
@stockmind I really cannot setting external screen dpi, I use linuxmint 18.2 Cinnamon 64bit

**Comment by stockmind** [comment]
Check this and select "Normal DPI" after external screen is connected. 
You can restore DPI selecting "High DPI" when you are done.
Let me know.

Follow install instructions.
https://github.com/stockmind/gpd-pocket-screen-indicator

**Comment by stockmind** [comment]
Using that indicator you can easily switch from High DPI to Normal DPI to work easily on attached monitors. Xorg doesn't manage well DPI on different screens. Wayland should fix this but performance on my end aren't really great.
