### ISSUE TITLE
ansible playbook - gnome desktop,use update.sh, touch rotation is wrong now

### ISSUE THREAD

**Issue by Xianbei233** [stockmind/gpd-pocket-ubuntu-respin#56]
As the title. and use the right command

**Comment by stockmind** [comment]
What distribution and kernel used?

Il 07 set 2017 11:09, "先辈" <notifications@github.com> ha scritto:

**Comment by Xianbei233** [comment]
this one: https://github.com/cawilliamson/ansible-gpdpocket
and more serious problem: abnormally cpu use 
![image](https://user-images.githubusercontent.com/16370242/30156435-3fef866c-93f2-11e7-95ff-33336b72e443.png)

**Comment by Xianbei233** [comment]
And scaling factor change can not  keep after reboot

**Comment by stockmind** [comment]
Ansible and this script aren't compatible. You must do a clean install or
remove files installed by ansible. I can try to figure out a clean script
for you but you need to wait tomorrow at least

Il 07 set 2017 11:34, "先辈" <notifications@github.com> ha scritto:

**Comment by Xianbei233** [comment]
thanks a lot. :)

**Comment by stockmind** [comment]
Check also this for your CPU usage:
https://askubuntu.com/questions/909591/systemd-resolve-high-cpu-usage-after-update-to-17-04

I'm not touching anything related to resolved.conf with my scripts or dnsmasq.

**Comment by stockmind** [comment]
Put this in a file and run as root:

``` 
#!/bin/bash

rm /etc/dconf/db/local.d/01scale
rm /etc/dconf/db/local.d/02subpixel
rm /etc/dconf/db/local.d/03scaling
rm /etc/dconf/db/local.d/03scaling
rm /etc/dconf/profile/gdm/profile
rm /etc/dconf/profile/user/profile
rm /etc/X11/Xsession.d/01gpd-rotate
rm /etc/X11/xinit/xinitrc.d/01gpd-rotate
rm /etc/gpd/rotate.conf
rm /usr/local/sbin/gpd-rotate
rm /etc/systemd/system/gpd-rotate.service
rm /etc/gpdfand.conf
rm /etc/X11/Xsession.d/01_touchegg
rm /etc/X11/xinit/xinitrc.d/01_touchegg
rm /etc/systemd/system/gpdfand.service
rm /etc/systemd/system/gpdrotate.service
rm /etc/udev/rules.d/99-local-bluetooth.rules
rm /etc/X11/xorg.conf.d/30-monitor.conf
rm /etc/X11/xorg.conf.d/80-screen.conf
rm /etc/X11/xorg.conf.d/89-screen.conf
rm /etc/X11/xorg.conf.d/90-monitor.conf
rm /etc/X11/xorg.conf.d/90-screen.conf
rm /etc/X11/Xsession.d/01gpdrotate
rm /etc/X11/Xsession.d/01touchscreen
rm /etc/X11/Xsession.d/02gpdrotate
rm /etc/X11/Xsession.d/02scale
rm /etc/X11/Xsession.d/03scaling
rm /etc/X11/Xsession.d/03scrolling
rm /etc/X11/Xsession.d/04gpdrotate
rm /etc/X11/Xsession.d/98gpdrotate
rm /etc/X11/Xsession.d/98touchscreen
rm /etc/X11/Xsession.d/99touchscreen
rm /lib/systemd/system-sleep/gpdfand
rm /root/ansible-gpdpocket
rm /usr/local/bin/gpdfand
rm /usr/local/bin/ansible-update
rm /usr/local/sbin/gpdfand
rm /usr/local/sbin/gpdrotate
rm /usr/src/linux-gpdpocket
rm /var/lib/gdm3/.config/monitors.xml
rm /var/lib/lightdm/.config/monitors.xml
rm /var/log/gpdfand
``` 

Run my **update.sh gnome** script again.
If problem persist checkout **dev** branch and run **update.sh gnome** script and **update-kernel.sh** script.

I've almost finished a little thing that may help you.

**Comment by stockmind** [comment]
Check this for scaling https://github.com/stockmind/gpd-pocket-ubuntu-respin#why-is-system-ui-so-big

**Comment by Xianbei233** [comment]
emmmmmmmmm,rolation problem still do not solved(remove old script failed)
![image](https://user-images.githubusercontent.com/16370242/30162790-c506d7ae-9408-11e7-94e7-51862d9235fd.png)

**Comment by stockmind** [comment]
Report result of 

    ls /usr/local/sbin
    ls /usr/local/bin

Then run

    gpdtouch

and check if touch is ok!

**Comment by Xianbei233** [comment]
run gpdtouch get result right but not work

and login screen rolation gets wrong (more problem

**Comment by stockmind** [comment]
Pull latest dev branch and run update.sh, check if touch is ok and if login screen is correctly rotated.
If touch is ok but login is in portrait i have a fix.
I'll update everything and merge master in the next days with a little utility for any DE user.

**Comment by stockmind** [comment]
Check this and try it.
Pull latest changes as i said above from the ubuntu respin repo and use:

    sudo update.sh gnome

Then download and install this.
Let me know.
On my end it works great with Unity, GNOME, XFCE, LXDE and KDE.

https://github.com/stockmind/gpd-pocket-screen-indicator

**Comment by stockmind** [comment]
Checked different config and GNOME is ok for me. Rotation can also be fixed using the indicator. I close it for now until further notice.
