### ISSUE TITLE
system  freezes

### ISSUE THREAD

**Issue by huangtao00** [stockmind/gpd-pocket-ubuntu-respin#6]
After operating a few minutes (about 15 minutes), the system freezes. Without any response when press any keyboard. the only way is to force to press power off button. Anyone  happen to hit this situation?

**Comment by snazzybunny** [comment]
I would try an older kernel. Hans updated the kernel and it's very unstable now.

**Comment by scofieldpeng** [comment]
yeah, i face the same problem and the system i respin is Liunux Mint 18.2 for mate, the system will freezes when i open the brower(chrome and firefox) after a few seconds

**Comment by huangtao00** [comment]
I have tested all the browsers, both Chrome and Firefox.  I found that the system will freeze only when using chrome and chromium. Using firefox is ok. I think maybe the the google`s browser is not compatible with the newest kernel.

**Comment by stockmind** [comment]
Try this stable kernel: https://drive.google.com/open?id=0B8-M0eiR7v8sRkZPOGxiUXpHMjQ

Extract in a folder then run "sudo dpkg -i *.deb"

Check on boot that the right kernel is selected. Or select secondo grub boot option and boot from RC7 kernel.

**Comment by stockmind** [comment]
Launch this 

    sudo apt-get purge linux-image-4.12.0-custom* linux-headers-4.12.0-custom*

This will remove old kernel files.

Then download and install this:
http://ge.tt/85TkCpl2

Extract in folder then use this to install:

    sudo dpkg -i *.deb

**Comment by guidouil** [comment]
I'm on Kernel 4.13-rc1-custom after `apt-get update` and `apt-get dist-upgrade` and I also experience the freezes after running chrome or firefox. Should I go back to 4.12 kernel that you pointed to ? thanks

**Comment by stockmind** [comment]
Are you using the one i've compiled?

Be sure to update your GRUB config

    sudo sed -i "s/GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash\"/GRUB_CMDLINE_LINUX_DEFAULT=\"\"/" /etc/default/grub
    sudo sed -i "s/GRUB_CMDLINE_LINUX=\"\"/GRUB_CMDLINE_LINUX=\"i915.fastboot=1 i915.semaphores=1\"/" /etc/default/grub

    sudo update-grub

Also update /etc/X11/xorg.config.d/20-intel with latest in git repo:

    git clone https://github.com/stockmind/gpd-pocket-ubuntu-respin.git
    cd gpd-pocket-ubuntu-respin/display/
    sudo cp 20-intel.conf /etc/X11/xorg.conf.d/20-intel.conf

Then add this on environment:

    sudo echo "COGL_ATLAS_DEFAULT_BLIT_MODE=framebuffer" >> /etc/environment
    sudo echo "LIBGL_DRI3_DISABLE=1" >> /etc/environment

Reboot and report. 

Force DRI2 seems to keep things more stable. 4.13 is still a work in progress and Hans seems working on power charging handle, but it still not done.

**Comment by stockmind** [comment]
Just reinstalled from latest Ubuntu ISO i'm uploading right now on Mega.
Stressed test with browser benchmark on Chrome for ten minutes with Youtube video in HD stream on other tab. Tried also to stream two/three video in HD on full screen. 
No hangs or crash so far.
Just need to check if using GPD while charging trigger crash or hangs.
Grub settings, intel xorg and environment flags should do the trick and keep system stable.
Hope i'm not talking too early!

**Comment by stockmind** [comment]
After an hour of use crashes just start to happen again. Frequency also seems to not work correctly on 4.13. 
I've just reverted my installation to 4.12 rc7, first link in this thread, frequencies are working again correctly and i'm waiting for hangs.

**Comment by guidouil** [comment]
So I should use your new ISO or old ISO, can you update your Link ? I think the respin done by a friend might be the issue here... For now I hate to say it but I'm back on windows :(

**Comment by stockmind** [comment]
Latest ISO of 20170725 Is fine. I've also wrote an update script to update
old installations. It Will take care only of respin done with my scripts.
It's not reccomended for others respin or systems updated with chrisaw
ansible playbook.

Il 25 lug 2017 10:33, "Guillaume Darbonne" <notifications@github.com> ha
scritto:

**Comment by guidouil** [comment]
ok I confirm it all work well with your iso from the 25th 
I'm typing this on my new preferred Linux laptop in chrome and without any freeze so far. Sleep works too :)

**Comment by Maokei** [comment]
I have freezing issue with the latest 20170725 iso seem to happen pretty soon after opening a browser.

**Comment by Maokei** [comment]
I can repeat the same results as @guidouil no issues after using the latest build.

**Comment by stockmind** [comment]
Just trying a new built kernel based on Hans 4.13rc2! The brcmfmac patch seems to work well and seems to have fixed the crashes.

**Comment by stockmind** [comment]
Latest kernel files: http://ge.tt/3y4Kpxl2
Extract in a folder then run:

    sudo dpkg -i *.deb

**Comment by scofieldpeng** [comment]
the fast charge problem has been sloved yet on Hans 4.13rc2?

**Comment by stockmind** [comment]
Not yet, but based on commits fix for charging are going on.

**Comment by guidouil** [comment]
@stockmind I have this warning in `W: Possible missing firmware /lib/firmware/i915/kbl_huc_ver02_00_1810.bin for module i915` when installing the latest kernel. I am willing to ignore it, but just to make sure it is mentioned somewhere :smiley:

**Comment by stockmind** [comment]
This warning means that the driver references the firmware but that it isn't installed. Maybe Intel has not yet pushed out this firmware to upstream linux-firmware. You can ignore it at the moment!

**Comment by stockmind** [comment]
Kernel updated, issue closed
