### ISSUE TITLE
TTY console text is way too small / resolution too high

### ISSUE THREAD

**Issue by ThuggishNuggets** [stockmind/gpd-pocket-ubuntu-respin#60]
The TTY console resolution is just way too high.

#### `GRUB_GFXMODE`
I've tried setting the `GRUB_GFXMODE` in `/etc/default/grub` and running `sudo update-grub` to no avail (that only changes the initial boot console and looks awful).

#### `sudo dpkg-reconfigure console-setup`
Using `sudo dpkg-reconfigure console-setup` and setting the font to the largest size (`16`) also doesn't do anything.

I'm guessing there's a script somewhere that is overriding the resolution once the greeter is shown, because the lock screen is [sometimes] an appropriate resolution (when locked manually). So there definitely seems to be some misconfiguration somewhere.

With such a high resolution monitor coupled with the small form factor, it makes using the TTY consoles a huge pain, and honestly you just look ridiculous hunched over a tiny laptop so you can read the console output.

Anyone have any ideas on how to fix this or where to look for clues?

**Comment by stockmind** [comment]
Just tried different approaches but no success yet. 

    because the lock screen is [sometimes] an appropriate resolution (when locked manually).

This makes me wonder if you have messed up with "video=" arguments in GRUB or something like that. On intel video driver you should get always the right resolution for lock screen (Lock screen in High DPI). You get a full resolution (Default DPI) only when modesetting driver get loaded on my experience. I can reproduce this messing around with boot args and video args. This also gives me tearing on normal usage.

**Comment by ThuggishNuggets** [comment]
Yeah, I haven't messed with any settings in GRUB with the sole exception being running `update.sh` and where I explicitly called out setting `GRUB_GFXMODE` trying to fix this, a change that has since been reverted.

This issue has persisted since day 1 with my GPD Pocket. I never installed using the respin image, since using the respin's `update.sh` script resolved most of the issues. I haven't had the time to dig through all of the changes between the two images to know if that would have an effect.

**Comment by stockmind** [comment]
Try to pull latest changes. Font in tty should be fixed on latest commit

**Comment by ThuggishNuggets** [comment]
Sorry been slammed at work with end of sprint crunch. I'll give it a run this weekend. Thanks man!

**Comment by stockmind** [comment]
Check also the updated kernel with USB C data support!

Updated kernel:
https://bitbucket.org/simone_nunzi/gpdpocket-kernel/downloads/gpdpocket-20170921-kernel-files.zip

You can install it using update_kernel.sh script here
https://github.com/stockmind/gpd-pocket-ubuntu-respin/blob/master/update-kernel.sh

**Comment by ThuggishNuggets** [comment]
@stockmind Was able to update using [`update.sh`](https://github.com/stockmind/gpd-pocket-ubuntu-respin/blob/master/update.sh) and the resolution issue is resolved. So much better!

Were these changes to the kernel that fixed this or was it more configuration file changes?

Either way. You rock man!

**Comment by ThuggishNuggets** [comment]
@stockmind [wrote](https://github.com/stockmind/gpd-pocket-ubuntu-respin/issues/60#issuecomment-331332772):
> Check also the updated kernel with USB C data support!

Also updated the kernel using [`update-kernel.sh`](https://github.com/stockmind/gpd-pocket-ubuntu-respin/blob/master/update-kernel.sh) and everything appears to be working very smoothly, although there is still some audio crackling/low-level noise, but that's not due to the update, I've always experienced that issue since i got my GPD Pocket.

Haven't tested USB-C data support yet, but I intend to.
