### ISSUE TITLE
gpdscreen-indicator tray bar icon missing

### ISSUE THREAD

**Issue by dlford** [stockmind/gpd-pocket-ubuntu-respin#62]
On Ubuntu 16.04, tray bar icon can be brought up from command line using ```gpdscreen-indicator```, but does not show up on reboot.  This morning I tried another ```git pull && sudo ./update.sh```, some changes were pulled but the issue persists.

Output of ```sudo ./update.sh```:

```
Display setting: Xorg-Standard
Remove conflicting packages...
Reading package lists...
Building dependency tree...
Reading state information...
Package 'bcmwl-kernel-source' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Install required packages...
Reading package lists...
Building dependency tree...
Reading state information...
python is already the newest version (2.7.11-1).
python-gi is already the newest version (3.20.0-0ubuntu1).
gksu is already the newest version (2.0.2-9ubuntu1).
i965-va-driver is already the newest version (1.7.0-1).
libva1 is already the newest version (1.7.0-1).
tlp is already the newest version (0.8-1).
va-driver-all is already the newest version (1.7.0-1).
vainfo is already the newest version (1.7.0-1).
gir1.2-appindicator3-0.1 is already the newest version (12.10.1+16.04.20170215-0ubuntu1).
git is already the newest version (1:2.7.4-0ubuntu1.2).
thermald is already the newest version (1.5-2ubuntu4).
gstreamer1.0-libav is already the newest version (1.8.3-1ubuntu0.2).
gstreamer1.0-vaapi is already the newest version (1.8.3-1~ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Remove old configuration files...
Update display files...
Patching lightdm files...
Patching default gnome 3 xrandr files...
Adding envrironment variables to prevent glitches...
Environment variable COGL_ATLAS_DEFAULT_BLIT_MODE already set
Environment variable LIBGL_DRI3_DISABLE already set
REBOOT REQUIRED!
Update GPD Fan daemon
Check modules...
pwm-lpss module already present
pwm-lpss-platform module already present
btusb module already present
Update/Install network files...
brcmfmac module already in SUSPEND_MODULE
Update/Install audio files...
set card profile already ok!
set card sink already ok!
set sink port already ok!
```

**Comment by stockmind** [comment]
I've made some tests and i'm trying to figure out the problem at boot. Maybe a delay at boot could help. Can you try to add it to your startup application in the meanwhile? Add the command "gpdscreen-indicator" to "Startup Applications" utility of Ubuntu. Let me know if it works at boot!

**Comment by dlford** [comment]
@stockmind Adding ```gpdscreen-indicator``` to Startup Apps is a successful workaround, I will leave it this way until I hear more.  For what it's worth, while I don't completely understand the whole of your code, I can't seem to find what is supposed to call ```gpdscreen-indicator``` at boot, looking at ```/etc/systemd/system/gpdscreen.service```, on line 7 ```ExecStart=/usr/local/sbin/gpdscreen service &```, isn't that the old service it's calling?  If it is still in use, I can't find any reference to ```gpdscreen-indicator``` inside of ```/usr/local/sbin/gpdscreen```

**Comment by stockmind** [comment]
There is a script in /etc/X11/Xsession.d/99-gpdscreen-indicator that get executed at boot time and launch gpdscreen. I've tested clean system of Ubuntu Unity and Ubuntu Gnome on 17.04 and no issue, i also get the same problem as you with Ubuntu Unity 16.04. 
https://github.com/stockmind/gpd-pocket-screen-indicator/blob/master/xsession/99-gpdscreen-indicator

Can you try to add a sleep before the command in that file ?
Something like:

    sleep 5 && /usr/local/sbin/gpdscreen-indicator &

Then reboot and wait! Just to see if another instance of the indicator spawn, you should see two after that if you keep your "Startup Applications" config as it is now.

**Be careful to keep the last & or your system may get stuck, and you may need to change tty and edit the file manually from nano or vim**

**Comment by dlford** [comment]
No joy, also tried ```sleep 30 &&...```, and tried renaming that file to ```99z-gpdscreen-indicator```, and ```10-gpdscreen-indicator```.  May be unrelated but here is what I found in ```~/.xsession-errors```:
```
openConnection: connect: No such file or directory
cannot connect to brltty at :0
No such schema 'org.cinnamon.desktop.interface'
No such schema 'org.cinnamon.desktop.interface'
No such schema 'org.cinnamon.desktop.interface'
```

**Comment by stockmind** [comment]
Try to update again! I've just changed the way it get launched relaying on autostart like others indicators. if you get only one istance after boot, try to remove your launch setting in Startup Application and reboot again, check if it works :)

**Comment by dlford** [comment]
Still no joy out of the box, I will tinker with it a bit when I get some time.

**Comment by Xianbei233** [comment]
ubuntu 17.04 gnome get same problem

**Comment by stockmind** [comment]
@Xianbei233 check that extension for legacy traybar icons is installed https://github.com/stockmind/gpd-pocket-ubuntu-respin#no-gpd-screen-rotation-icon-on-gnome-shell

**Comment by Xianbei233** [comment]
Failed to stop gpdtouch.service: Unit gpdtouch.service not loaded.
Failed to stop gpdtouch-wake.service: Unit gpdtouch-wake.service not loaded.
Failed to disable unit: No such file or directory
Failed to disable unit: No such file or directory
cp: cannot stat 'xsession/gpdscreen-indicator.desktop': No such file or directory
chmod: cannot access '/etc/xdg/autostart/gpdscreen-indicator.desktop': No such file or directory
REBOOT REQUIRED!

**Comment by stockmind** [comment]
My bad now it's clear why is not working. Will fix that asap

**Comment by stockmind** [comment]
I've missed to push latest commit, should be fixed now

**Comment by Xianbei233** [comment]
problem solved by https://github.com/stockmind/gpd-pocket-ubuntu-respin#no-gpd-screen-rotation-icon-on-gnome-shell, nice work.
By the way, after icon miss , i try to use update.sh to reinstall it but show that message.
at all, thanks for your works

**Comment by stockmind** [comment]
glad to hear that! you're welcome!

**Comment by stockmind** [comment]
@dlford do you mind to test again with latest commit? i just missed the "important" file 😅

**Comment by paqwak** [comment]
Hello,

Linux rookie here,

I'm running ubuntu hotel release from Nexus511, and after using your update script (post install), the gpdscreen-indicator tray bar is working fine.(it wasn't the case 2 days ago)

What if I want to set the highdpi preset to a scale of 2.25x ? (so I can use my device without glasses =o)). I need a full description about the file to edit, like if I was 6 ! 

Thanks a lot for your work on the pocket !

**Comment by dlford** [comment]
Working now, thank you! But - the orange charge indicator light on the power button is now stuck on (well, it's pulsing like it normally does when charging, but it does this even when the charger is not plugged in), should I mark this as solved and create a new ticket for that issue?

**Comment by stockmind** [comment]
That should depend to kernel and bios combo

Il 26 set 2017 22:09, "DL Ford" <notifications@github.com> ha scritto:

**Comment by dlford** [comment]
Weird, it wasn't doing that before and nothing has changed except ```git pull``` and ```sudo ./update.sh```

**Comment by stockmind** [comment]
Mhmh odd. The only thing that update do is copy required files for wifi and
audio other than setting things for video driver, nothing related or that
should change the behavior of that led

Il 26 set 2017 22:11, "DL Ford" <notifications@github.com> ha scritto:
