### ISSUE TITLE
No bluetooth adapter found after kernel-upgrade

### ISSUE THREAD

**Issue by MartinWeigl** [stockmind/gpd-pocket-ubuntu-respin#64]
After upgrading my kernel from 4.13 to 4.14.0-rc1 my system is no longer detecting the internal bluetooth adapter. I am using a respinned Kubuntu 17.04
Already did an update from a fresh cloned repository, but that made no difference.

On update i also got following three notifications:
W: Possible missing firmware /lib/firmware/i915/kbl_huc_ver02_00_1810.bin for module i915
W: Possible missing firmware /lib/firmware/i915/bxt_huc_ver01_07_1398.bin for module i915
W: Possible missing firmware /lib/firmware/i915/skl_huc_ver01_07_1398.bin for module i915

**Kernel:** 4.14.0-rc1-gpdpocket
**Desktop Environment:** Plasma 5.10
**Display:** :0
**Monitor:** DSI1 connected primary 1920x1200+0+0 right (normal left inverted right x axis y axis) 95mm x 151mm
**Scripts:**  adduser.local gpdfand gpdscreen gpdscreen-indicator
**EFI:**  [ 0.000000] efi: EFI v2.40 by American Megatrends
**EFI**  Release Date: 08/07/2017

**Comment by KeyHui** [comment]
No bluetooth adapter found after kernel-upgrade @stockmind

**Comment by leledumbo** [comment]
The actual cause seems to be:
```
hci0: Direct firmware load for brcm/BCM4354A2-0000-0000.hcd failed with error -2
hci0: BCM: Patch brcm/BCM4354A2-0000-0000.hcd not found
```

**Comment by stockmind** [comment]
Use previous kernel 4.13-rc5 if you need bluetooth for the moment and wait for updates.
Or try mainline kernel 4.14-rc2, you can download and install it using "ukuu" https://github.com/teejee2008/ukuu

**Comment by KeyHui** [comment]
@stockmind  I try to use 4.12-rc2, bluetooth can be use. but wifi cannot be use. 
so I only restore to 4.13-rc5

**Comment by stockmind** [comment]
Hans has just released a patch for bluetooth and explained everything here:
https://github.com/nexus511/gpd-ubuntu-packages/issues/26#issuecomment-333575775
I can make a kernel build tonight and update for real the iso with a full working kernel

**Comment by leledumbo** [comment]
Great news! As I have cloned his repo (oh, boy, 2.11 GB of almost 6 millions files containing source code, Linux devs are surely gifted) I guess I can build and install the kernel myself? It produces dpkg ready .deb files anyway.

**Comment by stockmind** [comment]
Yep. Follow kernel build section to build a kernel and install it yourself.

Il 02 ott 2017 19:05, "Mario Ray Mahardhika" <notifications@github.com> ha
scritto:

**Comment by leledumbo** [comment]
Even bluetooth audio works now. Kinda stuttering (tested by watching youtube), but at least it lasts more than 10 seconds.

**Comment by stockmind** [comment]
Kernel version updated to 4.14-rc3. Try it with update-kernel.sh script or download it and install and let me know. I cannot test it until GPD reply to my assistance request and repair my Pocket.

**Comment by MartinWeigl** [comment]
I can confirm, with kernel 4.14-rc3 bluetooth adapter is working again. Issue is solved THX!
