### ISSUE TITLE
Freeze when overheating

### ISSUE THREAD

**Issue by leledumbo** [stockmind/gpd-pocket-ubuntu-respin#66]
The default gpdfand.conf seems to be too liberal to the point that it can make the pocket freeze when the temperature reaches some hot point (I noticed it's 75 or something). I set a criteria that if geekbench4 can be run until finished without freezing, then the config is good. It's easy to get one that simply passes that criteria (e.g. set TURBO=50, you're done, but the turbo frequency is barely used at all), but I guess most of us also wants the best out of the CPU. A better solution is if course to be able to avoid the freeze, but I'm currently out of the clue how. I'm on unlocked BIOS with thermal mods applied (except replacing thermal paste, which I'm gonna do tomorrow).

**Comment by stockmind** [comment]
I can almost confirm that I had this kind of crash only on unlocked bios.
On any other bios on systems 17.04+ no issues no hangs.

Il 29 set 2017 15:15, "Mario Ray Mahardhika" <notifications@github.com> ha
scritto:

**Comment by leledumbo** [comment]
I see, that could be the reason. I hope they release the BIOS source code so we can tweak it as well. Anyway, this is the best config I've tested so far:
```
TIME=5
TURBO=60 # set it to 65 and the whole system will freeze at SGEMM Multi-Core test
MIN=50
MED=55
MAX=60
```
I will try on latest (locked) BIOS to see if the issue is gone with default gpdfand.conf.
I guess someone has made it through the best of the SoC (mine is on the right):
https://browser.geekbench.com/v4/cpu/compare/3907383?baseline=4268720

**Comment by leledumbo** [comment]
Latest locked BIOS freezes even faster at SQLite Multi-Core test, so I confirm that it's not BIOS problem.

**Comment by stockmind** [comment]
Could you attach problem reporting script report? 16.04 or 17.04 system?

Il 29 set 2017 16:04, "Mario Ray Mahardhika" <notifications@github.com> ha
scritto:

**Comment by leledumbo** [comment]
sure:
```
**Kernel:** 4.14.0-rc1-gpdpocket
**Desktop Environment:** 
**Display:** :0
**Monitor:** DSI1 connected primary 1920x1200+0+0 right (normal left inverted right x axis y axis) 95mm x 151mm
**Scripts:**  gpdfand gpdscreen gpdscreen-indicator
**EFI:**  [ 0.000000] efi: EFI v2.40 by American Megatrends
**EFI**  Release Date: 06/28/2017
```
17.04 system. You can try running geekbench yourself and see if it affects your system as well or my unit is simply f**ked up.

**Comment by stockmind** [comment]
Thank you, i really wish but my system just fucked up two days ago. I have to send it back as it just died (screen off, no signals, only power led, already tried to plug out and in battery or replug cables and pins). Probably defective mainboard, i had some problems on first days that just reappared recently. I'm one of the first bakers that have received it back in June, so first generation. I'm still waiting a reply from GPD. 
I can only share my experience of latest months where i had problems only with this scheme: 
BIOS unlocked (1600 Mhz ram) + any system = crash or random hangs of entire system, no tty working
BIOS locked + 16.04 systems = crash or random hangs of entire system or system some times really slow - need to change tty and relaunch X when system got slow and unusable
BIOS locked + 17.04 systems = fine no issues stressing it with HD video or kernel compile (really stressing), but never tried to do a benchmark with geekbench

Do you mind to test with kernel 4.13-rc5 and locked bios?
You also succeed in doing a kernel build?

**Comment by leledumbo** [comment]
> Do you mind to test with kernel 4.13-rc5 and locked bios?

OK, that can be done, but I still believe the issue is not in the kernel or BIOS. The protection mechanism is built into the CPU (I just read Intel manual that explains the feature) and the best way to avoid freeze is to avoid overheating in the first place. What problem could happen if I set TIME config to 1 second (with the hope that the fan isn't too late to cool the CPU down)?

> You also succeed in doing a kernel build?

No problem there, it just takes quite some time (I left it building while I go to sleep).

**Comment by stockmind** [comment]
With TIME at 1 you will probably stress more battery/cpu as every second the daemon will check and probably issue commands for fan speed change if you are around the "changing speed" temps. Geekbench stress graphics too? You can build kernel without problems, and kernel build on my device take the temps to 70 till done. So CPU is hot but no freeze. CPU protection should activate on overheating case, but overheating on that CPU isn't fixed at 90 degree? 
Any change the problem might be related to unsupported openGL calls?
There are some environment variables that let you change the openGL version used by video driver.
Our video card use for default a version that emulate lot of calls by software because the hardware can't manage those as far as i know/understood (And that should be the reason for such a sluggish/slow GNOME shell experience).

**Comment by leledumbo** [comment]
> Geekbench stress graphics too?

Nope.

> CPU protection should activate on overheating case, but overheating on that CPU isn't fixed at 90 degree?

What I know is that's the case for desktop CPU, for Atom I haven't found any info. But I really think it's 75, I monitor the temp while the benchmark is going. It never touches 75 if it passes without freezing, while when it doesn't, it could be 75 but I don't get the chance to see it (freezes already).

> Any change the problem might be related to unsupported openGL calls?

I don't think so.

**Comment by leledumbo** [comment]
"Fixes" found. Simply disable DPTF at all in BIOS, that's what freezes the system before it reaches the hardcoded factory limit of 90 (found this one, too). Now I can get maximum performance without system freeze despite the temp reaching 81. I'm happy now!

**Comment by stockmind** [comment]
Great! thanks for feedback and research! :) I will add it to troubleshooting section! Bios unlocked required right?

**Comment by leledumbo** [comment]
> Bios unlocked required right?

For sure

**Comment by peteh** [comment]
I there a way to enable always on fan when charging in the unlocked bios? I think that is what they changed in the release after the unlocked bios.

**Comment by leledumbo** [comment]
> I there a way to enable always on fan when charging in the unlocked bios?

Haven't found any, sorry. Better change the thermal paste (I tell you, this really helps a lot as the default one is really bad) if you want better heat dissipation.
