### ISSUE TITLE
Audio pops.

### ISSUE THREAD

**Issue by jmverges** [stockmind/gpd-pocket-ubuntu-respin#68]
I have the audio in the headphones and it pops. I look for auto-mute in alsamixer but not controls where found.

**Comment by stockmind** [comment]
We are aware of audio problems and might be related to the audio bug: https://github.com/stockmind/gpd-pocket-ubuntu-respin#what-doesnt-work-at-the-moment
Do it pops also in Windows with latest audio driver?

**Comment by stockmind** [comment]
As reported by Andre H. Beckedorf  here https://bugzilla.kernel.org/show_bug.cgi?id=196351#c25 i've builded a kernel based on Hans repository changing that flag:
https://bitbucket.org/simone_nunzi/gpdpocket-kernel/downloads/gpdpocket-20171010-kernel-files-audio-fix.zip

Try this and report. Also check if you enconter same pop in Windows to be sure its not driver related.

**Comment by jmverges** [comment]
Thank you, I don't have windows to test it. Do I need to install those .deb in a specific order? Cheers.

**Comment by stockmind** [comment]
Nope extract in a folder and run

    dpkg -i *.deb

 in that folder. Or download and run the update-kernel.sh script of this
repository

Il 11 ott 2017 09:34, "Juan Manuel Vergés Solanas" <notifications@github.com>
ha scritto:

**Comment by jmverges** [comment]
it stills pops and glitches with headphones output :( anybody else is having this problem?

**Comment by stockmind** [comment]
Are you sure that it booted on right kernel?

Can you post problem reporting again? Sorry for the double check, just to
be sure

Il 11 ott 2017 18:28, "Juan Manuel Vergés Solanas" <notifications@github.com>
ha scritto:

**Comment by jmverges** [comment]
**Kernel:** 4.13.0-rc3-custom-battery
**Desktop Environment:** 
**Display:** :0
**Monitor:** DSI1 connected primary 1920x1200+0+0 right (normal left inverted right x axis y axis) 95mm x 151mm
**Scripts:**  gpdfand gpdscreen gpdscreen-indicator
**EFI:**  [ 0.000000] efi: EFI v2.40 by American Megatrends
**EFI**  Release Date: 05/26/2017

**Comment by jmverges** [comment]
sudo ./update.sh           
Display setting: Xorg-Standard
Remove conflicting packages...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'bcmwl-kernel-source' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Install required packages...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-appindicator3-0.1 is already the newest version (12.10.1+17.04.20170215-0ubuntu1).
python is already the newest version (2.7.13-2).
python-gi is already the newest version (3.22.0-2).
gksu is already the newest version (2.0.2-9ubuntu1).
gstreamer1.0-libav is already the newest version (1.10.4-1).
gstreamer1.0-vaapi is already the newest version (1.10.4-1build1).
i965-va-driver is already the newest version (1.7.3-1).
libva1 is already the newest version (1.7.3-2).
tlp is already the newest version (0.9-3).
va-driver-all is already the newest version (1.7.3-2).
vainfo is already the newest version (1.7.3-2).
xfonts-terminus is already the newest version (4.40-2).
git is already the newest version (1:2.11.0-2ubuntu0.3).
thermald is already the newest version (1.5.4-4ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Remove old configuration files...
Update display files...
Patching lightdm files...
Patching default gnome 3 xrandr files...
Adding envrironment variables to prevent glitches...
Environment variable COGL_ATLAS_DEFAULT_BLIT_MODE already set
Environment variable LIBGL_DRI3_DISABLE already set
Cloning into 'gpd-pocket-screen-indicator'...
remote: Counting objects: 263, done.
remote: Total 263 (delta 0), reused 0 (delta 0), pack-reused 263
Receiving objects: 100% (263/263), 124.33 KiB | 0 bytes/s, done.
Resolving deltas: 100% (149/149), done.
Failed to stop gpdtouch.service: Unit gpdtouch.service not loaded.
Failed to stop gpdtouch-wake.service: Unit gpdtouch-wake.service not loaded.
Failed to disable unit: No such file or directory
Failed to disable unit: No such file or directory
REBOOT REQUIRED!
Update GPD Fan daemon
Check modules...
pwm-lpss module already present
pwm-lpss-platform module already present
btusb module already present
i915 module already present
Update console setup
Update modules of last kernel
update-initramfs: Generating /boot/initrd.img-4.13.0-rc3-custom-battery
W: Possible missing firmware /lib/firmware/i915/kbl_huc_ver02_00_1810.bin for module i915
W: Possible missing firmware /lib/firmware/i915/bxt_huc_ver01_07_1398.bin for module i915
W: Possible missing firmware /lib/firmware/i915/skl_huc_ver01_07_1398.bin for module i915
Update/Install network files...
brcmfmac module already in SUSPEND_MODULE
Update/Install audio files...
set card profile already ok!
set card sink already ok!
set sink port already ok!
Generating grub configuration file ...
Warning: Setting GRUB_TIMEOUT to a non-zero value when GRUB_HIDDEN_TIMEOUT is set is no longer supported.
Found linux image: /boot/vmlinuz-4.13.0-rc3-custom-battery
Found initrd image: /boot/initrd.img-4.13.0-rc3-custom-battery
Found linux image: /boot/vmlinuz-4.10.0-37-generic
Found initrd image: /boot/initrd.img-4.10.0-37-generic
done

**Comment by leledumbo** [comment]
> Found linux image: /boot/vmlinuz-4.13.0-rc3-custom-battery
> Found initrd image: /boot/initrd.img-4.13.0-rc3-custom-battery
> Found linux image: /boot/vmlinuz-4.10.0-37-generic
> Found initrd image: /boot/initrd.img-4.10.0-37-generic

You haven't installed the fixed kernel, that must be of version 4.14.0-rc3. Run ./update-kernel.sh instead of ./update.sh, both scripts are independent, running one won't run the other.

**Comment by stockmind** [comment]
Audio should be fully working now without pops or issues! :)
