### ISSUE TITLE
how to adjust the acceleration of mouse cursor controlled by trackpoint 

### ISSUE THREAD

**Issue by huangtao00** [stockmind/gpd-pocket-ubuntu-respin#7]
The mouse cursor controlled by trackpoint is awkward. please do you know how to adjust the acceleration of the mouse cursor controlled by trackpoint? hope for your reply.

**Comment by stockmind** [comment]
You can try this:

    xinput --set-prop 10 275 1

You can see the difference using this:

    xinput --set-prop 10 275 -1

First one will accelerate the pointer, second one will decelerate it.
1 is the max value. ATM don't know if it can be accelerated more.

**Comment by huangtao00** [comment]
> meyou@meyou-pocket:~$  xinput --set-prop 10 275 1
>property '275' doesn't exist, you need to specify its type and format

it seems that the property for device 10 does not exist. is this method suitable for your devices?

**Comment by stockmind** [comment]
Try:

    xinput --list-props 10

Look for input acceleration.
And report result of this:

    xinput list

**Comment by huangtao00** [comment]
thx  a lot. It woks for the property id=277. As follows:

>  xinput --set-prop  10  277 1

but the maximum acceleration is set by 1. what i want is much faster than that. do  you know any idea?

**Comment by stockmind** [comment]
Don't know of any other method ATM.

**Comment by maxengel** [comment]
I too have this issue, and unfortunately changing the speed in Ubuntu settings has no effect. Do you think there is a chance of getting the mouse speed setting working?

**Comment by stockmind** [comment]
The problem is that the trackpoint isn't a mouse. I've never had a ThinkPad or something but searching on Google didn't helped too much. I can only suggest that trick that will accelerate just a bit the pointer. 
Also you can try a different shape for the "nipple" as it may help to have better grip on it. 
Dragging the "nipple" with two fingers on my system give me a good acceleration. So maybe with a different shape and grip it may be possible to use it better with the correct and expected one-finger use.

**Comment by maxengel** [comment]
On elementary OS, there is a "Pointer Speed" option, but this doesn't impact the speed of moving the cursor.

**Comment by huangtao00** [comment]
the command below works for me. Maybe it will help someone.

> sudo xinput --set-prop  10  270 200

**Comment by petrmatula190** [comment]
I spend aroundx 15 minutes witch this easy task. This maybe help someone better.

`xinput --list-props 10`
search id on Accel Speed (it will be 1st oprion)

 `xinput --set-prop 10 id 1`
where id is from Accel Speed, 1 is maximum value

**Comment by stockmind** [comment]
@huangtao00 could you report to what property is associated your 270 id ?

**Comment by rustige** [comment]
Scaling the x- and y-Axis via the 'Coordinate Transformation Matrix' (id 142) and maxing 'Accel Speed' (id 275)  works very well for me:
```
# Coordinate Transformation Matrix
xinput --set-prop 10 142 2, 0, 0, 0, 2, 0, 0, 0, 1

# Accel Speed
xinput --set-prop 10 275 1
```
Change the 1st and 5th value only in the first command. The higher the values the higher the speed of the cursor. Leave the last value at 1! Otherwise there won't be any effect.

Result:
```
$ xinput --list-props 10
Device 'SINO WEALTH Gaming Keyboard':
	Device Enabled (140):	1
	Coordinate Transformation Matrix (142):	2.000000, 0.000000, 0.000000, 0.000000, 2.000000, 0.000000, 0.000000, 0.000000, 1.000000
	libinput Accel Speed (275):	1.000000
	libinput Accel Speed Default (276):	0.000000
	libinput Accel Profiles Available (277):	1, 1
	libinput Accel Profile Enabled (278):	0, 1
	libinput Accel Profile Enabled Default (279):	1, 0
	libinput Natural Scrolling Enabled (280):	0
	libinput Natural Scrolling Enabled Default (281):	0
	libinput Send Events Modes Available (260):	1, 0
	libinput Send Events Mode Enabled (261):	0, 0
	libinput Send Events Mode Enabled Default (262):	0, 0
	libinput Left Handed Enabled (282):	0
	libinput Left Handed Enabled Default (283):	0
	libinput Scroll Methods Available (284):	0, 0, 1
	libinput Scroll Method Enabled (285):	0, 0, 0
	libinput Scroll Method Enabled Default (286):	0, 0, 0
	libinput Button Scrolling Button (287):	2
	libinput Button Scrolling Button Default (288):	2
	libinput Middle Emulation Enabled (289):	0
	libinput Middle Emulation Enabled Default (290):	0
	Device Node (263):	"/dev/input/event4"
	Device Product ID (264):	9610, 273
	libinput Drag Lock Buttons (291):	<no items>
	libinput Horizontal Scroll Enabled (292):	1
```

**EDIT**
After finding the values that you like write them to `/etc/X11/xorg.conf.d/40-trackpoint.conf`. That way your settings survive a restart.
```
# /etc/X11/xorg.conf.d/40-trackpoint.conf
Section "InputClass"
    Identifier  "SINO WEALTH Gaming Keyboard"
    Option "TransformationMatrix" "2 0 0 0 2 0 0 0 1"
    Option "AccelSpeed" "1"
EndSection
```

**Comment by MartinWeigl** [comment]
rustige`s solution is working perfectly for me. Maybe you could include this into the respin itself or provide it as optional script, as this makes the device much easier to use.

**Comment by stockmind** [comment]
Thanks for tips i was leaving this open until I get this integrated into
the screen indicator so you can manage the speed of trackpoint easily from
a menu

Il 18 set 2017 19:17, "martinUSINGubuntu" <notifications@github.com> ha
scritto:

**Comment by SCDealy** [comment]
A warning for anyone who is using synergy for managing multiple computers/displays, altering the Coordinate Transform Matrix to fix your Trackpoint acceleration can completely break synergy (affects at least versions 1.4.18 to 1.8.8) I just filed the synergy bug yesterday and am looking for other alternatives to fix my trackpoint acceleration.
