### ISSUE TITLE
External HDMI displays not working with Ubuntu17.10FB.

### ISSUE THREAD

**Issue by x2eliah** [stockmind/gpd-pocket-ubuntu-respin#72]
This affects the final beta of Ubuntu17.10, using the current  'audiofix' kernel grabbed by the build script, respinned and updated with the 'gnome' parameter. (c.f. same config as on the appindicator issue from yesterday).
Moreover, I don't fully know if it's a Wayland problem, 17.10 problem, respin-modification problem, or a combination thereof. Might become easier to check for after 17.10 is officially released next week.

# Short: 
Plugging in a HDMI monitor rotates the built-in display, breaks the screen-indicator-rotator functionalities, shows an incorrectly positioned subset of screen on the external monitor, and ubuntu display settings don't seem to do much (Extend displays -> no changes can be applied, mirror or use-external-display-only renders the device unusable.)

# More info:
1. Tried with two (working) displays, using a (working) micro-hdmi to DVI-D bridge, a 1280x1024 and a 1920x1080 display.
2. Initial HDMI plug-in (after boot/login ofc):
  - GPD display rotates sideways. This persists even after disconnecting the hdmi display. _Reboot solves it._
![20171013_094737_hdr](https://user-images.githubusercontent.com/32734282/31535865-f35ec0b6-affc-11e7-8606-aed77744fa5b.jpg)

  - Display Indicator applet no longer does anything, no matter what option is clicked. This persists after disconnecting the hdmi display. _Reboot solves it._
  - The picture on external monitor is 'zoomed-in', showing a subset of the full "2nd monitor" screenspace in settings. 
![20171013_094741](https://user-images.githubusercontent.com/32734282/31535884-0330af04-affd-11e7-967f-b472b4f4472b.jpg)

3. (With ext. monitor plugged in) Ubuntu Settings->Devices->Displays does not apply changes correctly (**could be a 17.10fb/wayland bug**)
  - In 'Join Displays' mode, there's no way to apply any of the orientation changes (the 'apply' button does not show. (If going to other modes, making changes to show the 'apply' icon and switching back to 'join displays' mode, and hitting apply -> same mess as described below.
![20171013_094851](https://user-images.githubusercontent.com/32734282/31535959-43d34468-affd-11e7-9a2b-df4b3a04180a.jpg)
- In 'Mirror' or 'Single Display' modes, Applying the changes leads to corrupted (offset, misaligned) show on 2nd display and switched-off - or similarly off-aligned- builtin display.
![20171013_094947](https://user-images.githubusercontent.com/32734282/31536132-d9057f06-affd-11e7-87dc-f21eb18802f8.jpg)

**Comment by x2eliah** [comment]
Update: Of course, Ubuntu Gnome 17.04 (respun and updated with 'gnome') flag, works properly - no display corruptions, correct display extensions etc.

Could it be that the 'gnome' display configs are not appropriate for Wayland-x-gnome?

**Comment by stockmind** [comment]
Can you post output of "xrandr" command when you have external display connected?

Also try to run "gpdscreen" command on a terminal while external display is connected and post output.

Thank you!

**Comment by x2eliah** [comment]
Respun the 17.10 release (with gnome flag), external displays appear to work normally.
