### ISSUE TITLE
YT fullscreen freeze

### ISSUE THREAD

**Issue by Vontux** [stockmind/gpd-pocket-ubuntu-respin#78]
Playing 1080p videos in fullscreen results in system freeze. Tested on YT and Dailymotion to confirm. Is persisting with latest kernel 4.13-rc5 kernel. Would appear https://github.com/stockmind/gpd-pocket-ubuntu-respin/issues/40 should remain open.

**Comment by stockmind** [comment]
Please follow problem reporting section, https://github.com/stockmind/gpd-pocket-ubuntu-respin#problem-reporting and update kernel with update-kernel.sh script

Let me know

**Comment by Vontux** [comment]
Already updated the kernel actually. Further testing showed it only appeared to occur when the DPI mode was set to High instead of Normal. This was tested on both Mate and Cinnamon on a Linux Mint 18.2 MATE  respin. When set to Normal, the issue did not recur. Would running the problem reporting script still be worthwhile?

**Comment by stockmind** [comment]
Yes post the output of the problem reporting script please, this will help me collect all the info for your current configuration of BIOS and system version.
On BIOS unlocked be sure to disable DPTF as per https://github.com/stockmind/gpd-pocket-ubuntu-respin#system-freeze-or-hangs-on-high-temperatures-high-load-or-randomly

**Comment by Vontux** [comment]
Ok, so I installed the unlocked BIOS and disabled DPTF in the thermal settings and now the issue seems to no longer be occurring. I can play 1080p videos in both normal and high DPI without issue on both MATE and Cinnamon. Guess that was the issue.

**Comment by stockmind** [comment]
Great!:)

**Comment by Vontux** [comment]
Thanks for the help and the and the project.
