### ISSUE TITLE
Blueetoth audio driver unstable

### ISSUE THREAD

**Issue by huangtao00** [stockmind/gpd-pocket-ubuntu-respin#8]
i have tested the bluetooth for headset. although i can connect the headset successfully, but no soud can output from the my bluetooth device.

**Comment by stockmind** [comment]
Cherry Trail and Bay Trail audio devices seems to have some trouble when using output different from "Speakers" or "Headphone" of the native driver.
When i select bluetooth headset video and audio streaming start to crash. Video won't play or go further.
Using native Speaker as output let the video play again without issues.

You can try fiddle a bit looking at this post:
https://askubuntu.com/questions/764273/ubuntu-16-04-wont-output-sound-to-bluetooth-headphones

Look at latest answers.

I succeed in listening audio for about 10 seconds on my Bluetooth headset then sound crashed.
Don't have too much time to test.

Let me know if you succeed!

**Comment by huangtao00** [comment]
i have tested all the methods as the link given. the result is the same as you said- succeed in listening audio for about 10 seconds. really frustrating result.

**Comment by stockmind** [comment]
Hopefully it will get addressed soon or later. Cherry Trail support seems just at first stage.

**Comment by mfkenson** [comment]
not only the audio, bluetooth mouse only worked 2-3 seconds after connected

**Comment by stockmind** [comment]
Report your configuration, kernel, distribution, bios.. etc.

No problem on my end with Bluetooth mouse. Check if your mouse works
correctly on Windows and check if it works correctly with other Linux
systems (using it at least for a full session of work).

Il 13 set 2017 18:12, "Kenson Leung W.K" <notifications@github.com> ha
scritto:

**Comment by stockmind** [comment]
Should be fixed on latest kernel 4.14-rc3
