### ISSUE TITLE
Scale configuration

### ISSUE THREAD

**Issue by brunns** [stockmind/gpd-pocket-ubuntu-respin#81]
The best display scaling factor is pretty subjective. For example, I prefer 1.5 to the 1.75 that respin gives me. Is it possible to configure this somewhere so I don't have to keep resetting it?

**Comment by stockmind** [comment]
I can arrange a config file to save the setting!
In the meanwhile you can simply put something like

    gsettings set com.ubuntu.user-interface scale-factor "{'DSI-1': 12, 'DSI1': 12}"

In a file called for example

    /etc/X11/Xsession.d/91-scale

The number define priority, so it will be executed after my scale setting
It can override any setting i will change or not until i figure the best way to save and handle the edit/make it persistent

Let me know!

**Comment by brunns** [comment]
That works perfectly, thank you.
