### ISSUE TITLE
Freezes with Linux Mint 18.2 Cinnamon

### ISSUE THREAD

**Issue by nicosensei** [stockmind/gpd-pocket-ubuntu-respin#83]
I have respinned Linux Mint 18.2 Cinnamon two days ago and I experience a lot of freezes that make the system completely unusable. It does not occur when using the live USB, but once installed on the Pocket.

I suspect that it has something to do with Cinnamon which is not very stable on Intel Graphics boards, or the Ubuntu version (still in 16.04).

18.3 is out, I will try it and report.

**Comment by jbeard4** [comment]
I also get random freezes that require a hard restart on the latest version of the already respun Ubuntu ISO for GPD Pocket (2017-10-17). I am running Mate desktop. I have not investigated the cause of this.

**Comment by stockmind** [comment]
Please follow the problem reporting section and post output of problem-reporting script, this will help investigate the issue and provide the correct support: https://github.com/stockmind/gpd-pocket-ubuntu-respin#problem-reporting

Have you already checked this? https://github.com/stockmind/gpd-pocket-ubuntu-respin#system-freeze-or-hangs-on-high-temperatures-high-load-or-randomly

What bios version are you using? (This is picked by the problem-reporting script)

Thanks!

**Comment by jbeard4** [comment]
Running stock BIOS. Thanks for the tip, I will try disabling DPTF.

**Comment by nicosensei** [comment]
Thanks for the tip, I will try too. What's weird is that I now run the latest Ubuntu from the downloads section (october 17th) and it is perfectly stable. But then maybe Mint has different thermal throttling settings. Definitely worth a try.

And by the way the same freezes happen on Mint 18.3.

**Comment by nicosensei** [comment]
I just checked, I have the default stock BIOS, completely locked. I am not able to disable DPTF.

**Comment by stockmind** [comment]
What default stock BIOS? First batch of production or second? What build date do you see?
Just for completeness, could you post output of problem-reporting script? 
Thanks!

**Comment by jbeard4** [comment]
First production batch for me. I am also unable to disable DPTF in this BIOS version.

**Comment by nicosensei** [comment]
Well, I flashed the 20170628 unlocked bios, disabled DPTF in the Thermal section of the bios settings, and reinstalled (dual boot - just to be safe) my respinned Linux Mint Cinnamon 18.3.

I'm pleased to report it runs very well, I haven't experienced any freeze in a couple of hours! Hooray!

I've installed _psensor_ to check CPU temps, as I was a little worried to disable DPTF. My cores haven't gone over 60°C, which is good, despite heavy usage (bunch of apt installs, downloads and long I/Os).

What a blast!

**Comment by uuner** [comment]
I have a suspicion that disabling DPTF is more of a workaround than a solution. I had this problem with freezes in Linux Mint 18.3 Mate. 
In my case the freeze was always preceded with several messages:
[drm:fw_domains_get [i915]] *ERROR* render: timed out waiting for forcewake ack request.

I have switched to Ubuntu without disabling DPTF and the problem stopped reproducing.
