### ISSUE TITLE
Grub is rotated

### ISSUE THREAD

**Issue by mmccool** [stockmind/gpd-pocket-ubuntu-respin#86]
Grub is rotated (top to the left) on my install.   This is odd since I see you use the "fbcon=rotate:1" in the grub config file, which I used on another system (the Miix 310, actually with the same processor as the GPD Pocket) to rotate both grub and the command consoles:
https://forums.lenovo.com/t5/Linux-Discussion/ubuntu-for-Miix-310-10ICR-Tablet/m-p/3921073#M10340

Here it seems to fix the command consoles and (most of) the boot messages, but not grub itself.

Could be a version issue; my previous experience on the Miix 310 was with 16.04.   That said, I'd rather have grub rotated than the consoles!

**Comment by petrmatula190** [comment]
Rotare main grub screen is not possible, because screen is designet for tablet. SW rotare ("fbcon=rotate:1" in grub config) can be aplicable after load basic code from kernel.

The same situation is for BIOS (UEFI).

**Comment by stockmind** [comment]
I agree with Petr, as far as I know, there is no way to rotate grub.
Grub doesn't simply support rotate and probably won't until someone writes all the required code and get it merged into grub.
That was asked in 2009 in the Grub devel, I cannot find recent news after that
https://lists.gnu.org/archive/html/grub-devel/2009-07/msg00546.html

Are you sure that Grub really rotates in your Miix 310?
Could you provide a before and after pictures?

GPD Pocket could have the same processor of the Miix 310 but the grub rotation problem is related to the display that natively is manufactured as portrait in the GPD. The Miix 310 instead seems to have a usual landscape LCD, I'm correct?

**Comment by mmccool** [comment]
Yes, I am really sure the grub was rotated to the correct landscape orientation in my Miix now... and before it was profile, before I used the fbcon setting.  I might have done something else tho... let me check my grub config file.    The Miix has a pretty normal LCD but like the GPD acts like a tablet by default (eg the Ubuntu splash screen comes up in profile and I still have not been able to fix that).

**Comment by mmccool** [comment]
Well, that's interesting.   I went back to my Miix, disabled fbcon, and grub is still in landscape, (but everything else went back to being rotated).  I must have been hallucinating.   Well, alrighty then, sorry to bother you all.

**Comment by mmccool** [comment]
User error.

**Comment by stockmind** [comment]
No problem! I was hoping I've missed something in latest grub versions :( 
Hopefully someday, if manufacturers continue to produce device with portrait LCD, interest in grub rotate may increase and some patch will be sorted out :)

**Comment by mmccool** [comment]
Yeah, I even went back to my published notes on the Miix and it says right there that "grub screen is, strangely, NOT rotated."  D'oh.  I do think a patch to grub to allow rotation would be useful (although that is a separate project).   Also would be handy for people who want to run their monitors in profile mode.

**Comment by ShapeShifter499** [comment]
I wonder if a "rotated" theme could be made for this.   Grub stays rotated but the theme gives the appearance that it's not rotated.

**Comment by chrisvouglou** [comment]
> I wonder if a "rotated" theme could be made for this. Grub stays rotated but the theme gives the appearance that it's not rotated.

I did that kind of homework years ago, when I wanted a horizontal GRUB menu like this:
![image](https://user-images.githubusercontent.com/50662930/57773109-e3242880-771f-11e9-9a89-3f51cc471a78.png)

Had to hack around GRUB source code tho. Changed "max visible options" from N to 1. :)

**Comment by chrisvouglou** [comment]
Given that, one can obviously tweak a similar theme for GPD.

Don't know if I wanna be that one... ;)

**Comment by stuaxo** [comment]
The last comment on the grub mailinglist was rejected because they asked for arbitrary rotation, 90, 180, 270 is a lot easier.

**Comment by ruthan** [comment]
I looke at some post how to fix it:
https://www.reddit.com/r/GPDPocket/comments/9sl9sp/grub_landscape_working/
https://www.reddit.com/r/GPDPocket/comments/9r7jnz/pocket_2_grub_not_display/

 Why are there only some resolutions? Why is not possible to use some native one  1280x720 .. or 640x360 (half). 

  From coding perspective once is 90 degress rotation implement and next - 180 and 270 would be very easy.
