### ISSUE TITLE
Graphic driver: Applications like Emacs are not correctly updated

### ISSUE THREAD

**Issue by sanenr9** [stockmind/gpd-pocket-ubuntu-respin#87]
Hello,

with my GPD Pocket i seem to have an issue:
Applications like Emacs are not correctly screen refreshed sometimes.
I first thought it is an emacs issue but then i found out that doing any kind of interaction with the kde desktop environment like alt + tab or windows key for showing the startmenu solves the issue temporarily (redrawing the screen).

Do you have any idea what the issue could be concerning the screen not correctly refreshing?

Thanks

**Comment by stockmind** [comment]
Hello!
Could you take a picture or screenshot next time it will occur?
Also can you post "problem-reporting" script output for completeness?
Thank you!

**Comment by sanenr9** [comment]
Hi,

it is actually quite difficult to make a really "ugly" screenshot, as pressing print button leads to screen refreshment.

But i managed to create these two:

Before:

![before](https://user-images.githubusercontent.com/13300752/34492570-87c56c02-efe8-11e7-8078-65c56a1e0d87.png)
Normally the text created should be shown with an iso timestamp, but instead the blue headline background is shown again.

Correct after pressing the refresh button:

![correct](https://user-images.githubusercontent.com/13300752/34492573-8cf46354-efe8-11e7-83d3-59820abdfa60.png)

Here is the output of problem-reporting:
**Kernel:** 4.14.0-rc3-audio-gpdpocket
**Desktop Environment:** 
**Display:** :0
**Monitor:** DSI1 connected primary 1920x1200+0+0 right (normal left inverted right x axis y axis) 95mm x 151mm
**Scripts:**  gpdfand gpdscreen gpdscreen-indicator
**EFI:**  [ 0.000000] efi: EFI v2.40 by American Megatrends
**EFI**  Release Date: 06/28/2017

**Comment by stockmind** [comment]
Report here content of "/etc/environment" file then try to comment out all the lines, reboot and test.
Let me know!

**Comment by sanenr9** [comment]
Hi, it seems to have removed the issue!
This is the content:

```
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local$
COGL_ATLAS_DEFAULT_BLIT_MODE=framebuffer
LIBGL_DRI3_DISABLE=1

```
After disabling. I will monitor it, but until now it is definitely heavily improved or even gone!

Thanks so much!
