### ISSUE TITLE
I hope you can provide a 17.10 ISO file

### ISSUE THREAD

**Issue by Kevin1996cn** [stockmind/gpd-pocket-ubuntu-respin#90]
Thank you very much for your contribution.

**Comment by ferlanero** [comment]
Here you have mine. Ubuntu Budgie 17.10. Best performance on GPD Pocket: [http://www.ubuntuleon.com/2018/01/actualizacion-20180111-adaptacion.html](http://www.ubuntuleon.com/2018/01/actualizacion-20180111-adaptacion.html)

**Comment by stockmind** [comment]
New ISO coming soon!

**Comment by stockmind** [comment]
New ISO are online and i've also added a new mirror! It should be easier now as MEGA could be a problem for bandwith and firewalls! Sorry if it took a while to update this
