### ISSUE TITLE
no sound output after update ubuntu to 17.10

### ISSUE THREAD

**Issue by Xianbei233** [stockmind/gpd-pocket-ubuntu-respin#91]
i have used any solution that i can find in google but all don't work. now i can be sure that the problem is not on the pulseaudio or alsa.
i run the command `dmesg` and found lot of error.

snd_pcm_update_hw_ptr0: 63 callbacks suppressed
[ 9676.995817] cht-bsw-rt5645 cht-bsw-rt5645: invalid position: , pos = -22, buffer size = 192000, period size = 96000
[ 9677.064124]  Audio Port: sst: error code = -22
[ 9677.064143] cht-bsw-rt5645 cht-bsw-rt5645: invalid position: , pos = -22, buffer size = 192000, period size = 96000
[ 9677.132469]  Audio Port: sst: error code = -22
[ 9677.132489] cht-bsw-rt5645 cht-bsw-rt5645: invalid position: , pos = -22, buffer size = 192000, period size = 96000
[ 9677.201061]  Audio Port: sst: error code = -22
[ 9677.201091] cht-bsw-rt5645 cht-bsw-rt5645: invalid position: , pos = -22, buffer size = 192000, period size = 96000
[ 9677.269743]  Audio Port: sst: error code = -22
[ 9677.269760] cht-bsw-rt5645 cht-bsw-rt5645: invalid position: , pos = -22, buffer size = 192000, period size = 96000
[ 9677.338086]  Audio Port: sst: error code = -22
[ 9677.338126] cht-bsw-rt5645 cht-bsw-rt5645: invalid position: , pos = -22, buffer size = 192000, period size = 96000
[ 9677.406735]  Audio Port: sst: error code = -22
[ 9677.406776] cht-bsw-rt5645 cht-bsw-rt5645: invalid position: , pos = -22, buffer size = 192000, period size = 96000
[ 9677.475451]  Audio Port: sst: error code = -22
[ 9677.475490] cht-bsw-rt5645 cht-bsw-rt5645: invalid position: , pos = -22, buffer size = 192000, period size = 96000
[ 9677.544083]  Audio Port: sst: error code = -22
[ 9677.544115] cht-bsw-rt5645 cht-bsw-rt5645: invalid position: , pos = -22, buffer size = 192000, period size = 96000
[ 9677.612431]  Audio Port: sst: error code = -22
[ 9677.612457] cht-bsw-rt5645 cht-bsw-rt5645: invalid position: , pos = -22, buffer size = 192000, period size = 96000
[ 9677.680832]  Audio Port: sst: error code = -22
[ 9677.749497]  Audio Port: sst: error code = -22
[ 9677.817941]  Audio Port: sst: error code = -22
[ 9677.886446]  Audio Port: sst: error code = -22
[ 9677.954880]  Audio Port: sst: error code = -22
[ 9678.023574]  Audio Port: sst: error code = -22
[ 9678.092183]  Audio Port: sst: error code = -22
[ 9678.160529]  Audio Port: sst: error code = -22
[ 9678.229143]  Audio Port: sst: error code = -22
[ 9678.300152]  Audio Port: sst: error code = -22
[ 9678.368528]  Audio Port: sst: error code = -22
[ 9678.437149]  Audio Port: sst: error code = -22
[ 9678.505889]  Audio Port: sst: error code = -22
[ 9678.574714]  Audio Port: sst: error code = -22
[ 9678.643331]  Audio Port: sst: error code = -22
[ 9678.711928]  Audio Port: sst: error code = -22
[ 9678.780550]  Audio Port: sst: error code = -22
[ 9678.849168]  Audio Port: sst: error code = -22
[ 9678.917790]  Audio Port: sst: error code = -22
[ 9678.986489]  Audio Port: sst: error code = -22
[ 9679.055107]  Audio Port: sst: error code = -22
[ 9679.123447]  Audio Port: sst: error code = -22
[ 9679.192052]  Audio Port: sst: error code = -22
[ 9679.260683]  Audio Port: sst: error code = -22
[ 9679.329058]  Audio Port: sst: error code = -22
[ 9679.397417]  Audio Port: sst: error code = -22
[ 9679.465999]  Audio Port: sst: error code = -22
[ 9679.534585]  Audio Port: sst: error code = -22
[ 9679.603187]  Audio Port: sst: error code = -22
[ 9679.671818]  Audio Port: sst: error code = -22
[ 9679.740502]  Audio Port: sst: error code = -22
[ 9679.809114]  Audio Port: sst: error code = -22
[ 9679.877738]  Audio Port: sst: error code = -22
[ 9679.946447]  Audio Port: sst: error code = -22
[ 9680.015078]  Audio Port: sst: error code = -22
[ 9680.083523]  Audio Port: sst: error code = -22
[ 9680.152149]  Audio Port: sst: error code = -22
[ 9680.220904]  Audio Port: sst: error code = -22
[ 9680.289775]  Audio Port: sst: error code = -22
[ 9680.358105]  Audio Port: sst: error code = -22
[ 9680.426874]  Audio Port: sst: error code = -22
[ 9680.495511]  Audio Port: sst: error code = -22
[ 9680.563942]  Audio Port: sst: error code = -22
[ 9680.632561]  Audio Port: sst: error code = -22
[ 9680.701184]  Audio Port: sst: error code = -22
[ 9680.769801]  Audio Port: sst: error code = -22
[ 9680.838499]  Audio Port: sst: error code = -22
[ 9680.907119]  Audio Port: sst: error code = -22
[ 9680.975739]  Audio Port: sst: error code = -22
[ 9681.044451]  Audio Port: sst: error code = -22
[ 9681.113071]  Audio Port: sst: error code = -22
[ 9681.181700]  Audio Port: sst: error code = -22
[ 9681.250076]  Audio Port: sst: error code = -22
[ 9681.318697]  Audio Port: sst: error code = -22
[ 9681.387325]  Audio Port: sst: error code = -22
[ 9681.456169]  Audio Port: sst: error code = -22
[ 9681.525028]  Audio Port: sst: error code = -22
[ 9681.593654]  Audio Port: sst: error code = -22
[ 9681.662139]  Audio Port: sst: error code = -22
[ 9681.730762]  Audio Port: sst: error code = -22
[ 9681.799454]  Audio Port: sst: error code = -22
[ 9681.868073]  Audio Port: sst: error code = -22
[ 9681.926595]  Audio Port: sst: error code = -22
[ 9681.926747]  Audio Port: sst: error code = -22
[ 9681.926782]  Audio Port: sst: error code = -22
[ 9681.926817]  Audio Port: sst: error code = -22
[ 9681.927306]  Audio Port: sst: error code = -22
[ 9681.927471]  Audio Port: sst: error code = -22
[ 9681.927560]  Audio Port: sst: error code = -22
[ 9681.931049]  Audio Port: sst: error code = -22
[ 9681.931151]  Audio Port: sst: error code = -22
[ 9681.931437]  Audio Port: sst: error code = -22
[ 9681.931522]  Audio Port: sst: error code = -22
[ 9681.932315]  Audio Port: sst: error code = -22
[ 9681.932630]  Audio Port: sst: error code = -22
[ 9681.933043]  Audio Port: sst: error code = -22
[ 9681.933134]  Audio Port: sst: error code = -22
[ 9685.924165]  Audio Port: sst: error code = -22
[ 9685.924195] snd_pcm_update_hw_ptr0: 77 callbacks suppressed
[ 9685.924212] cht-bsw-rt5645 cht-bsw-rt5645: invalid position: , pos = -22, buffer size = 192000, period size = 96000
[ 9686.937628]  Audio Port: sst: error code = -22
[ 9686.937667] cht-bsw-rt5645 cht-bsw-rt5645: invalid position: , pos = -22, buffer size = 192000, period size = 96000
[ 9687.978857] intel_sst_acpi 808622A8:00: Wait timed-out condition:0x0, msg_id:0x1 fw_state 0x3
[ 9687.978886] intel_sst_acpi 808622A8:00: fw returned err -16
[ 9689.002883] intel_sst_acpi 808622A8:00: Wait timed-out condition:0x0, msg_id:0x1 fw_state 0x3
[ 9689.002911] intel_sst_acpi 808622A8:00: fw returned err -16
[ 9690.026676] intel_sst_acpi 808622A8:00: Wait timed-out condition:0x0, msg_id:0x2 fw_state 0x3
[ 9690.026705] intel_sst_acpi 808622A8:00: fw returned err -16
[ 9690.026739] intel_sst_acpi 808622A8:00: free stream returned err -19
[ 9691.050731] intel_sst_acpi 808622A8:00: Wait timed-out condition:0x0, msg_id:0x1 fw_state 0x3
[ 9691.050760] intel_sst_acpi 808622A8:00: fw returned err -16
[ 9692.074952] intel_sst_acpi 808622A8:00: Wait timed-out condition:0x0, msg_id:0x1 fw_state 0x3
[ 9692.074981] intel_sst_acpi 808622A8:00: fw returned err -16
[ 9693.098801] intel_sst_acpi 808622A8:00: Wait timed-out condition:0x0, msg_id:0x1 fw_state 0x3
[ 9693.098829] intel_sst_acpi 808622A8:00: fw returned err -16
[ 9694.122678] intel_sst_acpi 808622A8:00: Wait timed-out condition:0x0, msg_id:0x1 fw_state 0x3
[ 9694.122707] intel_sst_acpi 808622A8:00: fw returned err -16

how can i fix it?

**Comment by stockmind** [comment]
No problem on fresh install of 17.10. 
There must be something wrong with your current config.
Have you already tried to run "update.sh" and "update-kernel.sh" script?
Also can you post the output of "problem-reporting.sh" script?
Thanks!

**Comment by Xianbei233** [comment]
ok, i will try it tomorrow.

**Comment by Xianbei233** [comment]
**Kernel:** 4.15.0-rc5-custom-matlala-3-1-2018
**Desktop Environment:** 
**Display:** :1
**Monitor:** DSI1 connected primary 1920x1200+0+0 right (normal left inverted right x axis y axis) 95mm x 151mm
**Scripts:**  gpdfand gpdscreen gpdscreen-indicator
**EFI:**  [ 0.000000] efi: EFI v2.40 by American Megatrends
**EFI**  Release Date: 08/07/2017

**Comment by Xianbei233** [comment]
i fixed it. just firmware_intel_sst lost
