### ISSUE TITLE
Feedback: Hibernation working

### ISSUE THREAD

**Issue by samyongsj** [stockmind/gpd-pocket-ubuntu-respin#93]
Hibernation is working using 
`sudo systemctl hibernate`

Thanks for all the work you have put into this. 

**Kernel:** 4.15.0-rc5-custom-matlala-3-1-2018
**Desktop Environment:** 
**Display:** :1
**Monitor:** DSI1 connected primary 1920x1200+0+0 right (normal left inverted right x axis y axis) 95mm x 151mm
**Scripts:**  gpdfand gpdscreen gpdscreen-indicator
**EFI:**  [ 0.000000] efi: EFI v2.40 by American Megatrends
**EFI**  Release Date: 08/07/2017

**Comment by stockmind** [comment]
Wow! Great to know! :) No issues?

**Comment by samyongsj** [comment]
No issues with hibernation, not even with an encrypted installation. =) I do have swap as large as my ram. However sleep drains the battery rather quickly (roughly 10% in 3 hours iirc). Which was what made me try hibernation in the first place.

**Comment by geek78** [comment]
Hi,

Have you made something to enable it ? I am on the last 17.10 from stockmind and my GPD restard few seconds after the sudo systemctl hibernate
Thansk for you help

**Comment by samyongsj** [comment]
Hello, can you copy and paste the output of your problem-reporting script? (refer to my first post) 
It will help us figure out what the problem is. I did not do anything special to enable hibernation. Do check if you have enough swap space; when you hibernate the amount of ram used + swap should not be larger than the amount of swap available. Other more experienced members please correct me if I am incorrect.

**Comment by geek78** [comment]
Thanks ;)
Here is my log. You can see that I loose also Wifi juste after the restart (have to reboot to have again wifi)  


> 

15:30:36 dbus-daemon: Successfully activated service 'org.gnome.Logs'
15:30:36 wpa_supplicant: wlp1s0: Failed to initialize driver interface
15:30:36 NetworkManager: <info>  [1516890636.8341] device (wlp1s0): supplicant interface state: starting -> down
15:30:36 wpa_supplicant: nl80211: deinit ifname=wlp1s0 disabled_11b_rates=0
15:30:36 NetworkManager: <error> [1516890636.8340] sup-iface[0x7f9abc007c80,wlp1s0]: error adding interface: wpa_supplicant couldn't grab this interface.
15:30:36 wpa_supplicant: nl80211: Could not set interface 'wlp1s0' UP
15:30:36 kernel: brcmfmac: brcmf_netdev_open: failed bus is not ready
15:30:36 NetworkManager: <warn>  [1516890636.8281] device (wlp1s0): re-acquiring supplicant interface (#2).
15:30:36 dbus-daemon: Activating service name='org.gnome.Logs'
15:30:35 gnome-software: running search with refine-flags=require-icon with timeout=60 with max-results=20 with search=jour on plugin=snap on apps system/package/ubuntu-artful-universe/desktop/org.gnome.PackageUpdater.desktop/*,system/package/ubuntu-artful-universe/desktop/org.kde.discover.desktop/*,system/package/ubuntu-artful-universe/desktop/com.hughski.ColorHug.FlashLoader.desktop/*,system/package/ubuntu-artful-universe/desktop/almanah.desktop/*,system/package/ubuntu-artful-universe/desktop/zim.desktop/*,system/package/ubuntu-artful-universe/desktop/lifeograph.desktop/*,system/package/ubuntu-artful-universe/desktop/cinnamon-settings-general.desktop/*,system/package/ubuntu-artful-universe/desktop/mate-system-log.desktop/*,system/package/ubuntu-artful-universe/desktop/gnome-system-log.desktop/*,system/package/ubuntu-artful-universe/desktop/activity-log-manager.desktop/*,system/package/ubuntu-artful-universe/desktop/gnome-activity-journal.desktop/*,system/package/ubuntu-artful-universe/desktop/org.tabos.roger/*,system/package/ubuntu-artful-main/desktop/org.gnome.Software.desktop/*,system/package/ubuntu-artful-main/desktop/update-manager.desktop/*,system/package/ubuntu-artful-main/desktop/software-properties-gtk.desktop/*,system/package/ubuntu-artful-main/desktop/software-properties-gnome.desktop/*,system/package/ubuntu-artful-main/desktop/org.gnome.Logs.desktop/* took 1303ms
15:30:35 packagekitd: resolve transaction /32_abaeadee from uid 1000 finished with success after 1124ms
15:30:34 gnome-software: failed to call gs_plugin_add_search on snap: Get https://api.snapcraft.io/api/v1/snaps/search?confinement=strict%2Cclassic&fields=anon_download_url%2Carchitecture%2Cchannel%2Cdownload_sha3_384%2Csummary%2Cdescription%2Cdeltas%2Cbinary_filesize%2Cdownload_url%2Cepoch%2Cicon_url%2Clast_updated%2Cpackage_name%2Cprices%2Cpublisher%2Cratings_average%2Crevision%2Cscreenshot_urls%2Csnap_id%2Clicense%2Cbase%2Csupport_url%2Ccontact%2Ctitle%2Ccontent%2Cversion%2Corigin%2Cdeveloper_id%2Cprivate%2Cconfinement%2Cchannel_maps_list&q=jour: dial tcp: lookup api.snapcraft.io on 127.0.0.53:53: server misbehaving
15:30:34 nautilus: Could not establish a connection to Tracker: Failed to load SPARQL backend: Le fichier de clés n’a pas de groupe « DomainOntology »
15:30:33 dbus-daemon: Successfully activated service 'org.gnome.Nautilus'
15:30:28 gsd-power: Error setting property 'PowerSaveMode' on interface org.gnome.Mutter.DisplayConfig: Le délai d’attente est dépassé (g-io-error-quark, 24)
15:30:27 systemd: Started Virtual filesystem metadata service.
15:30:27 dbus-daemon: Successfully activated service 'org.gtk.vfs.Metadata'
15:30:27 systemd: Starting Virtual filesystem metadata service...
15:30:27 dbus-daemon: Activating via systemd: service name='org.gtk.vfs.Metadata' unit='gvfs-metadata.service'
15:30:26 wpa_supplicant: wlp1s0: Failed to initialize driver interface
15:30:26 NetworkManager: <info>  [1516890626.8416] device (wlp1s0): supplicant interface state: starting -> down
15:30:26 wpa_supplicant: nl80211: Could not set interface 'wlp1s0' UP
15:30:26 NetworkManager: <error> [1516890626.8415] sup-iface[0x7f9abc007be0,wlp1s0]: error adding interface: wpa_supplicant couldn't grab this interface.
15:30:26 wpa_supplicant: Could not set interface wlp1s0 flags (UP): Resource temporarily unavailable
15:30:26 kernel: brcmfmac: brcmf_netdev_open: failed bus is not ready
15:30:26 kernel: net_ratelimit: 3 callbacks suppressed
15:30:26 NetworkManager: <warn>  [1516890626.8356] device (wlp1s0): re-acquiring supplicant interface (#1).
15:30:26 gnome-shell: Some code accessed the property 'dbusNodeImplementsInterfaces' on the module 'util'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
15:30:26 gnome-software: no app for changed ubuntu-appindicators@ubuntu.com
15:30:26 gnome-shell: WARNING: addSignalMethods is replacing existing [0x55e935a58b70 Gjs_ShowAppsIcon.dash-item-container] emit method
15:30:25 gdm-session-wor: gkr-pam: unlocked login keyring
15:30:19 ModemManager: <info>  Couldn't check support for device at '/sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0': not supported by any plugin
15:30:17 systemd: Stopped TLP suspend/resume.
15:30:17 kernel:  sda: sda1
15:30:16 systemd-udevd: Process '/usr/sbin/tlp auto' failed with exit code 4.
15:30:16 NetworkManager: <info>  [1516890616.6542] device (wlp1s0): supplicant interface state: starting -> down
15:30:16 wpa_supplicant: wlp1s0: Failed to initialize driver interface
15:30:16 kernel: brcmfmac: brcmf_netdev_open: failed bus is not ready
15:30:16 systemd: Stopping TLP suspend/resume...
15:30:16 NetworkManager: <info>  [1516890616.5630] manager: NetworkManager state is now DISCONNECTED
15:30:16 systemd: systemd-hibernate.service: Failed with result 'exit-code'.
15:30:16 systemd-logind: Operation 'sleep' finished.
15:30:16 rtkit-daemon: Demoted 1 threads.
15:30:16 systemd: Dependency failed for Hibernate.
15:30:16 rtkit-daemon: Successfully demoted thread 1709 of process 1709 (n/a).
15:30:16 systemd: Failed to start Hibernate

> 

And free -h give me 
 Mem : 1,0 G used - 5,6G free - 426M shared
Swap file : 0B used - 1,2G free



_

**Comment by geek78** [comment]
I have updated my grub cfg with values for resume and resume_offset. I have no more issue with wifi but a new error "Swap header not found!".
Don''t know if it is important but i am using a dual boot (win 10 and ubuntu)

**Comment by samyongsj** [comment]
Im not using dual boot fwiw. I'm sorry im totally out of my depth here.. perhaps stockmind can help. 
i found that its usually faster to shutdown and after boot, open the applications i need (the gpd pocket cant open too many at one go anyway) than restoring from hibernation. its not exactly good for the emmc either but of course its nice to be able to.

**Comment by geek78** [comment]
hi
after following this guide my pocket can hibernate !!! 
https://wiki.debian.org/Hibernation/Hibernate_Without_Swap_Partition and start at "Now use uswsusp"

**Comment by stockmind** [comment]
Great! I've updated the README accordingly! :) I link README to this and close for now.
