### ISSUE TITLE
How to get this active? https://github.com/stockmind/gpd-pocket-ubuntu-respin/pull/84

### ISSUE THREAD

**Issue by sanenr9** [stockmind/gpd-pocket-ubuntu-respin#99]
Hi Stockmind,

no idea what is the right handling for such kind of requests:

For the following: https://github.com/stockmind/gpd-pocket-ubuntu-respin/pull/84
Do i have to install the debs mentioned in that thread, so that the issue dissappears on my gpd pocket?
Or what is the best practice to get this running on my machine?
I assume, there is some kind of backgroud concept for automatic updates but i'm not sure, how this works.

Thank you so much.

Right now im on:
**Kernel:** 4.14.0-rc3-audio-gpdpocket
**Desktop Environment:** 
**Display:** :0
**Monitor:** DSI1 connected primary 1920x1200+0+0 right (normal left inverted right x axis y axis) 95mm x 151mm
**Scripts:**  gpdfand gpdscreen gpdscreen-indicator
**EFI:**  [ 0.000000] efi: EFI v2.40 by American Megatrends                            
**EFI**  Release Date: 06/28/2017

**Comment by stockmind** [comment]
Touchscreen have been fixed on latest kernels. Run "update-kernel.sh" script of this repository to update your kernel and fix the problem! :)

**Comment by sanenr9** [comment]
Thanks so much for the great work :D it works great!!
